import sys

heroes = """
export const collectionsHeroFallback = {
  id: 'fallback-ma-collections',
  pageKey: 'master-artisans-collections',
  autoplayEnabled: true,
  autoplayIntervalMs: 6000,
  slides: [
    {
      id: 'macoll-1',
      internalName: 'Heritage Collections',
      eyebrow: 'HERITAGE COLLECTIONS',
      titleLineOne: 'A LIVING',
      titleConnector: 'collection of',
      titleLineTwo: 'KASHMIR\\'S FINEST CRAFTS',
      description: 'Explore carefully documented collections preserving the artistry, history, provenance, and cultural significance of Kashmir\\'s most treasured handcrafted works.',
      primaryCtaLabel: 'Explore Collections',
      primaryCtaUrl: '#explore',
      secondaryCtaLabel: 'Collection Guide',
      secondaryCtaUrl: '#guide',
      tertiaryLinkLabel: 'Featured Objects',
      tertiaryLinkUrl: '#objects',
      meta1: 'Heritage',
      meta2: 'Provenance',
      meta3: 'Collections',
      meta4: 'Preservation'
    },
    {
      id: 'macoll-2',
      internalName: 'Curated Heritage',
      eyebrow: 'CURATED HERITAGE',
      titleLineOne: 'EVERY OBJECT',
      titleConnector: 'tells a',
      titleLineTwo: 'HUMAN STORY',
      description: 'Each collection celebrates extraordinary craftsmanship while preserving the stories, makers, materials, and traditions behind every masterpiece.',
      primaryCtaLabel: 'Browse Collection',
      primaryCtaUrl: '#browse',
      secondaryCtaLabel: 'Meet the Makers',
      secondaryCtaUrl: '#makers',
      tertiaryLinkLabel: 'Collection Essays',
      tertiaryLinkUrl: '#essays',
      meta1: 'Stories',
      meta2: 'Artisans',
      meta3: 'Legacy',
      meta4: 'Authenticity'
    },
    {
      id: 'macoll-3',
      internalName: 'Craft Legacy',
      eyebrow: 'CRAFT LEGACY',
      titleLineOne: 'PRESERVING',
      titleConnector: 'masterpieces for',
      titleLineTwo: 'FUTURE GENERATIONS',
      description: 'Building a permanent public archive that safeguards Kashmir\\'s finest craftsmanship through documentation, research, and responsible stewardship.',
      primaryCtaLabel: 'View Archive',
      primaryCtaUrl: '#archive',
      secondaryCtaLabel: 'Research Notes',
      secondaryCtaUrl: '#research',
      tertiaryLinkLabel: 'Museum Archive',
      tertiaryLinkUrl: '#museum',
      meta1: 'Archive',
      meta2: 'Documentation',
      meta3: 'Research',
      meta4: 'Conservation'
    },
    {
      id: 'macoll-4',
      internalName: 'The Collection Continues',
      eyebrow: 'THE COLLECTION CONTINUES',
      titleLineOne: 'FROM WORKSHOPS',
      titleConnector: 'to',
      titleLineTwo: 'WORLD HERITAGE',
      description: 'Connecting master artisans, collectors, museums, researchers, and future generations through one growing collection of excellence.',
      primaryCtaLabel: 'Latest Additions',
      primaryCtaUrl: '#latest',
      secondaryCtaLabel: 'Rare Objects',
      secondaryCtaUrl: '#rare',
      tertiaryLinkLabel: 'Contemporary Excellence',
      tertiaryLinkUrl: '#contemporary',
      meta1: 'Museums',
      meta2: 'Collectors',
      meta3: 'Heritage',
      meta4: 'Scholarship'
    }
  ]
};

export const signatureMasterpiecesHeroFallback = {
  id: 'fallback-signature-masterpieces',
  pageKey: 'signature-masterpieces',
  autoplayEnabled: true,
  autoplayIntervalMs: 6000,
  slides: [
    {
      id: 'sigmast-1',
      internalName: 'Signature Masterpieces',
      eyebrow: 'SIGNATURE MASTERPIECES',
      titleLineOne: 'THE PINNACLE',
      titleConnector: 'of',
      titleLineTwo: 'CRAFT EXCELLENCE',
      description: 'Exceptional works representing the highest achievements in craftsmanship, artistic vision, technical mastery, and cultural significance.',
      primaryCtaLabel: 'View Masterpieces',
      primaryCtaUrl: '#view',
      secondaryCtaLabel: 'Master Artisan Profiles',
      secondaryCtaUrl: '#profiles',
      tertiaryLinkLabel: 'Collection Catalogue',
      tertiaryLinkUrl: '#catalogue',
      meta1: 'Masterpieces',
      meta2: 'Excellence',
      meta3: 'Heritage',
      meta4: 'Authenticity'
    },
    {
      id: 'sigmast-2',
      internalName: 'Exceptional Craft',
      eyebrow: 'EXCEPTIONAL CRAFT',
      titleLineOne: 'WHERE TIME',
      titleConnector: 'becomes',
      titleLineTwo: 'ART',
      description: 'Celebrate extraordinary creations whose complexity, rarity, and beauty define the highest standards of Kashmir\\'s traditional craftsmanship.',
      primaryCtaLabel: 'Explore Works',
      primaryCtaUrl: '#explore',
      secondaryCtaLabel: 'Creative Process',
      secondaryCtaUrl: '#process',
      tertiaryLinkLabel: 'Craft Techniques',
      tertiaryLinkUrl: '#techniques',
      meta1: 'Creativity',
      meta2: 'Skill',
      meta3: 'Time',
      meta4: 'Perfection'
    },
    {
      id: 'sigmast-3',
      internalName: 'Iconic Collection',
      eyebrow: 'ICONIC COLLECTION',
      titleLineOne: 'MASTERWORKS',
      titleConnector: 'worthy of',
      titleLineTwo: 'GLOBAL RECOGNITION',
      description: 'Discover iconic objects admired for artistic excellence, historical value, exceptional provenance, and enduring cultural importance.',
      primaryCtaLabel: 'Museum Quality',
      primaryCtaUrl: '#museum',
      secondaryCtaLabel: 'Collector Notes',
      secondaryCtaUrl: '#notes',
      tertiaryLinkLabel: 'Object Archive',
      tertiaryLinkUrl: '#archive',
      meta1: 'Museums',
      meta2: 'Provenance',
      meta3: 'Recognition',
      meta4: 'Legacy'
    },
    {
      id: 'sigmast-4',
      internalName: 'Collector\\'s Edition',
      eyebrow: 'COLLECTOR\\'S EDITION',
      titleLineOne: 'THE FINEST',
      titleConnector: 'examples of',
      titleLineTwo: 'KASHMIR CRAFTSMANSHIP',
      description: 'A carefully curated showcase celebrating masterpieces that define the artistic identity of Kashmir across generations.',
      primaryCtaLabel: 'Browse Collection',
      primaryCtaUrl: '#browse',
      secondaryCtaLabel: 'Rare Highlights',
      secondaryCtaUrl: '#rare',
      tertiaryLinkLabel: 'Collection Essays',
      tertiaryLinkUrl: '#essays',
      meta1: 'Collectors',
      meta2: 'Heritage',
      meta3: 'Artistry',
      meta4: 'Excellence'
    }
  ]
};

export const museumArchiveHeroFallback = {
  id: 'fallback-museum-archive',
  pageKey: 'museum-archive',
  autoplayEnabled: true,
  autoplayIntervalMs: 6000,
  slides: [
    {
      id: 'musarch-1',
      internalName: 'Museum Archive',
      eyebrow: 'MUSEUM ARCHIVE',
      titleLineOne: 'PRESERVING',
      titleConnector: 'objects of',
      titleLineTwo: 'ENDURING VALUE',
      description: 'A museum-grade archive documenting historically significant masterpieces, their provenance, craftsmanship, and cultural importance.',
      primaryCtaLabel: 'Museum Archive',
      primaryCtaUrl: '#archive',
      secondaryCtaLabel: 'Historic Collections',
      secondaryCtaUrl: '#collections',
      tertiaryLinkLabel: 'Research Records',
      tertiaryLinkUrl: '#records',
      meta1: 'Museums',
      meta2: 'Provenance',
      meta3: 'Preservation',
      meta4: 'Scholarship'
    },
    {
      id: 'musarch-2',
      internalName: 'Curated for History',
      eyebrow: 'CURATED FOR HISTORY',
      titleLineOne: 'EVERY OBJECT',
      titleConnector: 'belongs to',
      titleLineTwo: 'OUR SHARED HERITAGE',
      description: 'Explore verified collections preserving Kashmir\\'s artistic achievements through scholarly documentation and responsible conservation.',
      primaryCtaLabel: 'Browse Archive',
      primaryCtaUrl: '#browse',
      secondaryCtaLabel: 'Collection History',
      secondaryCtaUrl: '#history',
      tertiaryLinkLabel: 'Museum Essays',
      tertiaryLinkUrl: '#essays',
      meta1: 'History',
      meta2: 'Conservation',
      meta3: 'Heritage',
      meta4: 'Collections'
    },
    {
      id: 'musarch-3',
      internalName: 'Documenting Excellence',
      eyebrow: 'DOCUMENTING EXCELLENCE',
      titleLineOne: 'FROM THE',
      titleConnector: 'past to',
      titleLineTwo: 'THE FUTURE',
      description: 'Museum-quality documentation ensures priceless cultural objects remain accessible to researchers, educators, and future generations.',
      primaryCtaLabel: 'Explore Records',
      primaryCtaUrl: '#records',
      secondaryCtaLabel: 'Digital Archive',
      secondaryCtaUrl: '#digital',
      tertiaryLinkLabel: 'Object Catalogue',
      tertiaryLinkUrl: '#catalogue',
      meta1: 'Documentation',
      meta2: 'Archives',
      meta3: 'Research',
      meta4: 'Education'
    },
    {
      id: 'musarch-4',
      internalName: 'Knowledge Preserved',
      eyebrow: 'KNOWLEDGE PRESERVED',
      titleLineOne: 'ARCHIVING',
      titleConnector: 'more than',
      titleLineTwo: 'OBJECTS',
      description: 'Every archived masterpiece preserves craftsmanship, historical context, artisan identity, and cultural memory.',
      primaryCtaLabel: 'View Collections',
      primaryCtaUrl: '#view',
      secondaryCtaLabel: 'Provenance Records',
      secondaryCtaUrl: '#provenance',
      tertiaryLinkLabel: 'Historic Essays',
      tertiaryLinkUrl: '#essays',
      meta1: 'Knowledge',
      meta2: 'Identity',
      meta3: 'Memory',
      meta4: 'Heritage'
    }
  ]
};

export const rareObjectsHeroFallback = {
  id: 'fallback-rare-objects',
  pageKey: 'rare-objects',
  autoplayEnabled: true,
  autoplayIntervalMs: 6000,
  slides: [
    {
      id: 'rareobj-1',
      internalName: 'Rare Objects',
      eyebrow: 'RARE OBJECTS',
      titleLineOne: 'EXCEPTIONALLY',
      titleConnector: 'rare and',
      titleLineTwo: 'IRREPLACEABLE',
      description: 'Explore remarkable handcrafted objects distinguished by rarity, historical significance, exceptional craftsmanship, and verified provenance.',
      primaryCtaLabel: 'Rare Collection',
      primaryCtaUrl: '#collection',
      secondaryCtaLabel: 'Object Registry',
      secondaryCtaUrl: '#registry',
      tertiaryLinkLabel: 'Collector Notes',
      tertiaryLinkUrl: '#notes',
      meta1: 'Rarity',
      meta2: 'Provenance',
      meta3: 'Heritage',
      meta4: 'Collections'
    },
    {
      id: 'rareobj-2',
      internalName: 'Extraordinary Discoveries',
      eyebrow: 'EXTRAORDINARY DISCOVERIES',
      titleLineOne: 'FEW REMAIN',
      titleConnector: 'to tell',
      titleLineTwo: 'THEIR STORY',
      description: 'Each rare object represents a unique chapter in Kashmir\\'s artistic history, preserved through careful research and documentation.',
      primaryCtaLabel: 'Explore Objects',
      primaryCtaUrl: '#explore',
      secondaryCtaLabel: 'Historical Context',
      secondaryCtaUrl: '#context',
      tertiaryLinkLabel: 'Museum Archive',
      tertiaryLinkUrl: '#archive',
      meta1: 'History',
      meta2: 'Discovery',
      meta3: 'Research',
      meta4: 'Legacy'
    },
    {
      id: 'rareobj-3',
      internalName: 'Collector Heritage',
      eyebrow: 'COLLECTOR HERITAGE',
      titleLineOne: 'WHERE',
      titleConnector: 'rarity meets',
      titleLineTwo: 'AUTHENTICITY',
      description: 'Verified masterpieces reflecting exceptional craftsmanship, scarce materials, historic importance, and outstanding cultural value.',
      primaryCtaLabel: 'View Highlights',
      primaryCtaUrl: '#highlights',
      secondaryCtaLabel: 'Authentication',
      secondaryCtaUrl: '#authentication',
      tertiaryLinkLabel: 'Craft Passport',
      tertiaryLinkUrl: '#passport',
      meta1: 'Collectors',
      meta2: 'Authenticity',
      meta3: 'Provenance',
      meta4: 'Excellence'
    },
    {
      id: 'rareobj-4',
      internalName: 'Enduring Value',
      eyebrow: 'ENDURING VALUE',
      titleLineOne: 'BEYOND',
      titleConnector: 'beauty lies',
      titleLineTwo: 'HISTORY',
      description: 'Discover how rarity, craftsmanship, and provenance combine to create enduring cultural treasures.',
      primaryCtaLabel: 'Rare Collection',
      primaryCtaUrl: '#collection',
      secondaryCtaLabel: 'Research Notes',
      secondaryCtaUrl: '#notes',
      tertiaryLinkLabel: 'Collection Essays',
      tertiaryLinkUrl: '#essays',
      meta1: 'Culture',
      meta2: 'Research',
      meta3: 'Value',
      meta4: 'Heritage'
    }
  ]
};

export const contemporaryExcellenceHeroFallback = {
  id: 'fallback-contemporary-excellence',
  pageKey: 'contemporary-excellence',
  autoplayEnabled: true,
  autoplayIntervalMs: 6000,
  slides: [
    {
      id: 'contexc-1',
      internalName: 'Contemporary Excellence',
      eyebrow: 'CONTEMPORARY EXCELLENCE',
      titleLineOne: 'TRADITION',
      titleConnector: 'reimagined for',
      titleLineTwo: 'TODAY',
      description: 'Celebrate artisans who preserve traditional knowledge while creating exceptional works that speak confidently to contemporary audiences.',
      primaryCtaLabel: 'Explore Excellence',
      primaryCtaUrl: '#explore',
      secondaryCtaLabel: 'Modern Masters',
      secondaryCtaUrl: '#masters',
      tertiaryLinkLabel: 'Latest Works',
      tertiaryLinkUrl: '#works',
      meta1: 'Innovation',
      meta2: 'Heritage',
      meta3: 'Design',
      meta4: 'Excellence'
    },
    {
      id: 'contexc-2',
      internalName: 'Today\\'s Masterpieces',
      eyebrow: 'TODAY\\'S MASTERPIECES',
      titleLineOne: 'WHERE',
      titleConnector: 'heritage inspires',
      titleLineTwo: 'INNOVATION',
      description: 'Exceptional contemporary craftsmanship demonstrates how tradition continues to evolve without compromising authenticity.',
      primaryCtaLabel: 'Featured Collection',
      primaryCtaUrl: '#featured',
      secondaryCtaLabel: 'Emerging Excellence',
      secondaryCtaUrl: '#emerging',
      tertiaryLinkLabel: 'Creative Process',
      tertiaryLinkUrl: '#process',
      meta1: 'Innovation',
      meta2: 'Authenticity',
      meta3: 'Creativity',
      meta4: 'Craft'
    },
    {
      id: 'contexc-3',
      internalName: 'Craft Without Compromise',
      eyebrow: 'CRAFT WITHOUT COMPROMISE',
      titleLineOne: 'THE FUTURE',
      titleConnector: 'built on',
      titleLineTwo: 'TRADITION',
      description: 'Modern masterpieces that honor centuries of craftsmanship while responding thoughtfully to contemporary design and global appreciation.',
      primaryCtaLabel: 'View Collection',
      primaryCtaUrl: '#view',
      secondaryCtaLabel: 'Master Profiles',
      secondaryCtaUrl: '#profiles',
      tertiaryLinkLabel: 'Design Essays',
      tertiaryLinkUrl: '#essays',
      meta1: 'Future',
      meta2: 'Heritage',
      meta3: 'Design',
      meta4: 'Identity'
    },
    {
      id: 'contexc-4',
      internalName: 'Global Craft Excellence',
      eyebrow: 'GLOBAL CRAFT EXCELLENCE',
      titleLineOne: 'FROM',
      titleConnector: 'Kashmir to',
      titleLineTwo: 'THE WORLD',
      description: 'Recognizing contemporary artisans whose work demonstrates exceptional craftsmanship and international relevance.',
      primaryCtaLabel: 'Global Showcase',
      primaryCtaUrl: '#showcase',
      secondaryCtaLabel: 'Featured Artisans',
      secondaryCtaUrl: '#artisans',
      tertiaryLinkLabel: 'Editorial Series',
      tertiaryLinkUrl: '#editorial',
      meta1: 'Global',
      meta2: 'Recognition',
      meta3: 'Excellence',
      meta4: 'Heritage'
    }
  ]
};

export const collectionEssaysHeroFallback = {
  id: 'fallback-collection-essays',
  pageKey: 'collection-essays',
  autoplayEnabled: true,
  autoplayIntervalMs: 6000,
  slides: [
    {
      id: 'colless-1',
      internalName: 'Collection Essays',
      eyebrow: 'COLLECTION ESSAYS',
      titleLineOne: 'UNDERSTANDING',
      titleConnector: 'the stories behind',
      titleLineTwo: 'THE COLLECTIONS',
      description: 'Scholarly essays exploring history, craftsmanship, symbolism, provenance, conservation, and the cultural significance of extraordinary collections.',
      primaryCtaLabel: 'Read Essays',
      primaryCtaUrl: '#read',
      secondaryCtaLabel: 'Featured Authors',
      secondaryCtaUrl: '#authors',
      tertiaryLinkLabel: 'Essay Archive',
      tertiaryLinkUrl: '#archive',
      meta1: 'Scholarship',
      meta2: 'Research',
      meta3: 'Heritage',
      meta4: 'Collections'
    },
    {
      id: 'colless-2',
      internalName: 'Curated Knowledge',
      eyebrow: 'CURATED KNOWLEDGE',
      titleLineOne: 'EVERY COLLECTION',
      titleConnector: 'deserves',
      titleLineTwo: 'DEEPER UNDERSTANDING',
      description: 'Thoughtfully researched writing connecting objects with history, artisans, communities, materials, and cultural meaning.',
      primaryCtaLabel: 'Explore Essays',
      primaryCtaUrl: '#explore',
      secondaryCtaLabel: 'Research Library',
      secondaryCtaUrl: '#library',
      tertiaryLinkLabel: 'Knowledge Hub',
      tertiaryLinkUrl: '#hub',
      meta1: 'Knowledge',
      meta2: 'History',
      meta3: 'Interpretation',
      meta4: 'Culture'
    },
    {
      id: 'colless-3',
      internalName: 'Research & Reflection',
      eyebrow: 'RESEARCH & REFLECTION',
      titleLineOne: 'LOOKING',
      titleConnector: 'beyond the',
      titleLineTwo: 'MASTERPIECE',
      description: 'Essays examining artistic context, historical relevance, conservation practices, and evolving perspectives on Kashmir\\'s heritage.',
      primaryCtaLabel: 'Latest Essays',
      primaryCtaUrl: '#latest',
      secondaryCtaLabel: 'Collection Research',
      secondaryCtaUrl: '#research',
      tertiaryLinkLabel: 'Editorial Archive',
      tertiaryLinkUrl: '#archive',
      meta1: 'Research',
      meta2: 'Context',
      meta3: 'Conservation',
      meta4: 'Heritage'
    },
    {
      id: 'colless-4',
      internalName: 'The Written Archive',
      eyebrow: 'THE WRITTEN ARCHIVE',
      titleLineOne: 'DOCUMENTING',
      titleConnector: 'knowledge for',
      titleLineTwo: 'THE FUTURE',
      description: 'Creating a permanent body of scholarship that enriches understanding of Kashmir\\'s master artisans and their extraordinary collections.',
      primaryCtaLabel: 'Essay Collection',
      primaryCtaUrl: '#collection',
      secondaryCtaLabel: 'Submit Research',
      secondaryCtaUrl: '#submit',
      tertiaryLinkLabel: 'Support Documentation',
      tertiaryLinkUrl: '#support',
      meta1: 'Documentation',
      meta2: 'Scholarship',
      meta3: 'Legacy',
      meta4: 'Future'
    }
  ]
};
