export const allMasters = [
  { slug: "zainab-begum", name: "Zainab Begum", craft: "Pashmina", loc: "Srinagar", award: "Emerging Talent", img: "/assets/images/artisans/pashmina_1.jpg", stage: "Sorting", desc: "Specializes in hand-sorting and cleaning raw white pashm wool fleece.", years: 12, sig: "Hand-sorting", bio: "Zainab Begum has been a dedicated artisan in the Pashmina craft for over a decade, focusing on the meticulous process of hand-sorting." },
  { slug: "hajira-begum", name: "Hajira Begum", craft: "Pashmina", loc: "Eidgah", award: "Padma Shri", img: "/assets/images/artisans/pashmina_2.jpg", stage: "Spinning", desc: "A master spinner on the traditional Yinder, creating ethereal threads.", years: 45, sig: "Fine Spinning", bio: "Hajira Begum is a Padma Shri awardee whose legendary spinning skills have produced some of the finest Pashmina threads." },
  { slug: "abdul-rashid", name: "Abdul Rashid", craft: "Pashmina", loc: "Kanihama", award: "State Award", img: "/assets/images/artisans/pashmina_3.jpg", stage: "Dyeing", desc: "Expert dyer utilizing natural crimson and indigo vats.", years: 30, sig: "Natural Dyeing", bio: "Abdul Rashid has spent decades perfecting the art of natural dyeing, bringing vibrant colors to life." },
  { slug: "ghulam-hassan", name: "Ghulam Hassan", craft: "Pashmina", loc: "Kanihama", award: "Padma Shri", img: "/assets/images/artisans/pashmina_4.jpg", stage: "Weaving", desc: "A Padma Shri awardee for his unmatched skill on the Kani handloom.", years: 50, sig: "Kani Weaving", bio: "Ghulam Hassan is a master weaver whose Kani shawls are celebrated globally for their intricate patterns." },
  
  { slug: "bashir-ahmad", name: "Bashir Ahmad", craft: "Walnut Carving", loc: "Safa Kadal", award: "State Award", img: "/assets/images/artisans/walnut_1.jpg", stage: "Selecting", desc: "The crucial first step: inspecting and measuring seasoned walnut logs.", years: 35, sig: "Log Selection", bio: "Bashir Ahmad's expertise in selecting the perfect walnut logs forms the foundation of masterpieces." },
  { slug: "ali-mohammad-najjar", name: "Ali Mohammad Najjar", craft: "Walnut Carving", loc: "Srinagar", award: "Shilp Guru", img: "/assets/images/artisans/walnut_2.jpg", stage: "Rough Chiseling", desc: "A Shilp Guru known for powerfully chiseling the initial rough forms.", years: 55, sig: "Rough Chiseling", bio: "Ali Mohammad Najjar is a Shilp Guru who shapes the initial forms with unmatched power and precision." },
  { slug: "mohammad-yusuf", name: "Mohammad Yusuf", craft: "Walnut Carving", loc: "Pampore", award: "National Award", img: "/assets/images/artisans/walnut_3.jpg", stage: "Fine Undercut", desc: "Masters the intricate 3D undercut carving technique.", years: 40, sig: "Undercut Carving", bio: "Mohammad Yusuf's fine undercut carving brings incredible depth and realism to his woodwork." },
  { slug: "firdous-ahmad", name: "Firdous Ahmad", craft: "Walnut Carving", loc: "Pampore", award: "Emerging Talent", img: "/assets/images/artisans/walnut_4.jpg", stage: "Polishing", desc: "Brings out the rich, dark wood grain with traditional polishing.", years: 15, sig: "Traditional Polishing", bio: "Firdous Ahmad is an emerging talent dedicated to the traditional techniques of wood polishing." },
  
  { slug: "shabir-hussain", name: "Shabir Hussain", craft: "Papier-Mâché", loc: "Zadibal", award: "Emerging Talent", img: "/assets/images/artisans/papier_1.jpg", stage: "Pounding Pulp", desc: "Vigorously pounds wet paper pulp in a traditional stone mortar.", years: 10, sig: "Pulp Pounding", bio: "Shabir Hussain brings youthful energy to the foundational step of Papier-Mâché creation." },
  { slug: "tariq-bhat", name: "Tariq Bhat", craft: "Papier-Mâché", loc: "Zadibal", award: "State Award", img: "/assets/images/artisans/papier_2.jpg", stage: "Sakhtsazi", desc: "Molds raw pulp over wooden forms to create the structural base.", years: 25, sig: "Sakhtsazi", bio: "Tariq Bhat's skill in Sakhtsazi ensures that every Papier-Mâché object has a perfect, durable base." },
  { slug: "mehmooda", name: "Mehmooda", craft: "Papier-Mâché", loc: "Safa Kadal", award: "National Award", img: "/assets/images/artisans/papier_3.jpg", stage: "Base Coat", desc: "Applies the smooth white Gutch base coat in preparation for painting.", years: 30, sig: "Gutch Application", bio: "Mehmooda's smooth base coats are the perfect canvas for the intricate Naqashi that follows." },
  { slug: "zahid-dar", name: "Zahid Dar", craft: "Papier-Mâché", loc: "Safa Kadal", award: "Shilp Guru", img: "/assets/images/artisans/papier_4.jpg", stage: "Naqashi", desc: "Paints microscopic gold floral patterns with incredible precision.", years: 45, sig: "Naqashi Painting", bio: "Zahid Dar is a Shilp Guru whose microscopic gold floral patterns are a testament to his incredible precision." },
  
  { slug: "umar-farooq", name: "Umar Farooq", craft: "Copperware", loc: "Zaina Kadal", award: "Emerging Talent", img: "/assets/images/artisans/copper_1.jpg", stage: "Forging", desc: "Forges and melts raw copper over an intensely hot open fire.", years: 8, sig: "Copper Forging", bio: "Umar Farooq is an emerging talent mastering the intense heat and heavy labor of copper forging." },
  { slug: "manzoor-ahmad", name: "Manzoor Ahmad", craft: "Copperware", loc: "Downtown", award: "Master Artisan", img: "/assets/images/artisans/copper_2.jpg", stage: "Hammering", desc: "Rhythmically hammers and shapes large vessels on an iron anvil.", years: 35, sig: "Rhythmic Hammering", bio: "Manzoor Ahmad's rhythmic hammering shapes copper into beautiful, functional vessels." },
  { slug: "naseem", name: "Naseem", craft: "Copperware", loc: "Downtown", award: "State Award", img: "/assets/images/artisans/copper_3.jpg", stage: "Kandkari", desc: "Engraves hyper-detailed arabesque patterns into the finished metal.", years: 28, sig: "Kandkari Engraving", bio: "Naseem's Kandkari engraving adds intricate beauty to everyday copperware." },
  { slug: "mushtaq-ali", name: "Mushtaq Ali", craft: "Copperware", loc: "Zaina Kadal", award: "Shilp Guru", img: "/assets/images/artisans/copper_4.jpg", stage: "Kalai", desc: "Performs the tinning process to coat the inside of copper pots.", years: 50, sig: "Kalai Tinning", bio: "Mushtaq Ali is a Shilp Guru whose Kalai tinning ensures the safety and longevity of copper vessels." },
  
  { slug: "riyaz-ahmad", name: "Riyaz Ahmad", craft: "Embroidery", loc: "Nowhatta", award: "Master Artisan", img: "/assets/images/artisans/embroidery_1.jpg", stage: "Tracing", desc: "A Naqash who traces complex paisley patterns onto tracing paper.", years: 40, sig: "Pattern Tracing", bio: "Riyaz Ahmad's precise pattern tracing sets the stage for the exquisite embroidery that follows." },
  { slug: "rifat-ara", name: "Rifat Ara", craft: "Embroidery", loc: "Srinagar", award: "National Award", img: "/assets/images/artisans/embroidery_2.jpg", stage: "Crewel", desc: "Executes Crewel work using a hooked Aari needle on a wooden frame.", years: 30, sig: "Crewel Embroidery", bio: "Rifat Ara's Crewel work is celebrated for its vibrant colors and meticulous execution." },
  { slug: "shamima", name: "Shamima", craft: "Embroidery", loc: "Eidgah", award: "Shilp Guru", img: "/assets/images/artisans/embroidery_3.jpg", stage: "Tilla Dozi", desc: "Couches metallic gold Tilla thread onto rich velvet fabrics.", years: 45, sig: "Tilla Dozi", bio: "Shamima is a Shilp Guru whose Tilla Dozi adds a touch of royal elegance to any fabric." },
  { slug: "fatima-begum", name: "Fatima Begum", craft: "Embroidery", loc: "Nowhatta", award: "Padma Shri", img: "/assets/images/artisans/embroidery_4.jpg", stage: "Sozni", desc: "Performs microscopic Sozni fine needlework on delicate shawls.", years: 55, sig: "Sozni Needlework", bio: "Fatima Begum is a Padma Shri awardee whose microscopic Sozni needlework is renowned worldwide." }
];

export const allIssues = [
  // 2026 (6 issues)
  { slug: "01", num: "01", title: "Women of the Loom", season: "Autumn", year: "2026", desc: "Exploring the silent backbone of Kashmiri craft: the women who spin, weave, and embroider from within their homes.", img: "/assets/images/issues/issue_1.jpg" },
  { slug: "02", num: "02", title: "The Copper Markets", season: "Summer", year: "2026", desc: "A photographic journey through the rhythmic, hammering lanes of Zaina Kadal and the evolution of Traam utensils.", img: "/assets/images/issues/issue_2.jpg" },
  { slug: "03", num: "03", title: "Papier-Mâché Geometries", season: "Spring", year: "2026", desc: "Decoding the intricate, mathematical precision of Naqashi patterns and the organic composition of the Sakhta base.", img: "/assets/images/issues/issue_3.jpg" },
  { slug: "09", num: "09", title: "The Silver Engravers", season: "Winter", year: "2026", desc: "Delving into the delicate art of silver engraving and the historic jewelers of downtown Srinagar.", img: "/assets/images/issues/issue_1.jpg" },
  { slug: "10", num: "10", title: "Modern Motifs", season: "Late Autumn", year: "2026", desc: "How contemporary designers are collaborating with traditional artisans to reinterpret the classic paisley.", img: "/assets/images/issues/issue_2.jpg" },
  { slug: "11", num: "11", title: "Sustainable Silk", season: "Early Spring", year: "2026", desc: "The resurgence of ethical silk farming and sustainable weaving practices in the valley.", img: "/assets/images/issues/issue_3.jpg" },

  // 2025 (6 issues)
  { slug: "04", num: "04", title: "The Walnut Legacy", season: "Winter", year: "2025", desc: "Tracing the lineage of undercut carving techniques and the slow, deliberate aging process of authentic Kashmiri walnut wood.", img: "/assets/images/issues/issue_4.jpg" },
  { slug: "05", num: "05", title: "Dyes of the Earth", season: "Autumn", year: "2025", desc: "The chemistry of natural dyes: madder root, walnut hull, and indigo, and the families who guard these secret recipes.", img: "/assets/images/issues/issue_5.jpg" },
  { slug: "06", num: "06", title: "The Talim Code", season: "Summer", year: "2025", desc: "Translating the complex shorthand script used to dictate Kani weaving patterns to the entire Karkhan.", img: "/assets/images/issues/issue_6.jpg" },
  { slug: "07", num: "07", title: "Reviving Waguv", season: "Spring", year: "2025", desc: "The endangered craft of river reed weaving and the environmental impact of losing the Dal Lake's natural materials.", img: "/assets/images/issues/issue_7.jpg" },
  { slug: "12", num: "12", title: "Kashmir the art of knot", season: "Late Summer", year: "2025", desc: "The geometric brilliance of interlocking wood pieces without a single nail.", img: "/assets/images/issues/issue_8.jpg" },
  { slug: "13", num: "13", title: "The Apprentice", season: "Early Winter", year: "2025", desc: "A look into the rigorous training and dedication required of a new apprentice in the master workshops.", img: "/assets/images/issues/issue_4.jpg" },

  // 2024 (6 issues)
  { slug: "08", num: "08", title: "The Silk Route", season: "Winter", year: "2024", desc: "Tracing the historical trade routes that brought Central Asian carpet weaving techniques into the heart of Srinagar.", img: "/assets/images/issues/issue_8.jpg" },
  { slug: "14", num: "14", title: "Crewel Explorations", season: "Autumn", year: "2024", desc: "The vibrant history of crewel embroidery and its journey to the European markets.", img: "/assets/images/issues/issue_5.jpg" },
  { slug: "15", num: "15", title: "The Felt Makers", season: "Summer", year: "2024", desc: "Inside the strenuous and rhythmic process of pressing raw wool into the iconic Namda rugs.", img: "/assets/images/issues/issue_6.jpg" },
  { slug: "16", num: "16", title: "Lost Techniques", season: "Spring", year: "2024", desc: "Documenting the forgotten stitches and carving styles that have vanished over the last century.", img: "/assets/images/issues/issue_7.jpg" },
  { slug: "17", num: "17", title: "The Artisan's Tool", season: "Late Autumn", year: "2024", desc: "A focus on the bespoke tools—from the Aari to the Chisel—that make masterpiece creation possible.", img: "/assets/images/issues/issue_8.jpg" },
  { slug: "18", num: "18", title: "Voices of the Elders", season: "Early Summer", year: "2024", desc: "Oral histories collected from the oldest surviving masters in the valley's craft quarters.", img: "/assets/images/issues/issue_1.jpg" }
];
