#Requires -Version 5.1
<#
.SYNOPSIS
    Pre-Deployment Evidence Capture — SKC Classification Subsystem
    HCR Foundation Project

.DESCRIPTION
    Run this script BEFORE making any changes to production.
    It captures the current Git SHA, target deployment SHA, Prisma migration
    status, environment variable checklist, and rollback information, then
    writes everything to a timestamped evidence file in the project root.

    No arguments required. Safe to run in any environment.

.NOTES
    Target deployment commit : 4e1b8a9
    Rollback tag             : v2026.07-skc-classification-certified
    Generated by: scripts/pre-deployment-evidence.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Helper — append to both console and the evidence buffer
# ---------------------------------------------------------------------------
$evidenceLines = [System.Collections.Generic.List[string]]::new()

function Write-Evidence {
    param([string]$Line = '')
    Write-Host $Line
    $evidenceLines.Add($Line)
}

function Write-EvidenceSeparator {
    Write-Evidence ('=' * 72)
}

function Write-EvidenceSection {
    param([string]$Title)
    Write-Evidence ''
    Write-EvidenceSeparator
    Write-Evidence "  $Title"
    Write-EvidenceSeparator
}

# ---------------------------------------------------------------------------
# Resolve project root (script lives in <root>/scripts/)
# ---------------------------------------------------------------------------
$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$BackendDir  = Join-Path $ProjectRoot 'backend'

$Timestamp      = Get-Date -Format 'yyyyMMdd_HHmmss'
$TimestampHuman = Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'
$EvidenceFile   = Join-Path $ProjectRoot "pre-deployment-evidence-$Timestamp.txt"

# ---------------------------------------------------------------------------
# HEADER
# ---------------------------------------------------------------------------
Write-EvidenceSeparator
Write-Evidence '  HCR FOUNDATION — SKC CLASSIFICATION SUBSYSTEM'
Write-Evidence '  PRE-DEPLOYMENT EVIDENCE CAPTURE'
Write-Evidence "  Generated : $TimestampHuman"
Write-EvidenceSeparator

# ---------------------------------------------------------------------------
# SECTION 1 — Git SHA (current HEAD)
# ---------------------------------------------------------------------------
Write-EvidenceSection 'SECTION 1 — CURRENT GIT SHA (HEAD)'

try {
    $currentSha = git -C $ProjectRoot rev-parse HEAD 2>&1
    if ($LASTEXITCODE -ne 0) { throw "git rev-parse failed: $currentSha" }
    $currentShaBranch = git -C $ProjectRoot rev-parse --abbrev-ref HEAD 2>&1
    Write-Evidence "  Current HEAD SHA : $currentSha"
    Write-Evidence "  Current Branch   : $currentShaBranch"
} catch {
    Write-Evidence "  [WARNING] Could not retrieve Git SHA: $_"
    $currentSha = 'UNKNOWN'
}

# ---------------------------------------------------------------------------
# SECTION 2 — Target Deployment SHA
# ---------------------------------------------------------------------------
Write-EvidenceSection 'SECTION 2 — TARGET DEPLOYMENT SHA'
Write-Evidence '  Target SHA (short) : 4e1b8a9'
Write-Evidence '  Release Tag        : v2026.07-skc-classification-certified'
Write-Evidence ''
Write-Evidence '  ACTION REQUIRED: Verify the above SHA matches your deployment'
Write-Evidence '  artifact / Docker image tag before proceeding.'

# ---------------------------------------------------------------------------
# SECTION 3 — Prisma Migration Status (pre-deployment)
# ---------------------------------------------------------------------------
Write-EvidenceSection 'SECTION 3 — PRISMA MIGRATION STATUS (PRE-DEPLOYMENT)'
Write-Evidence "  Working directory : $BackendDir"
Write-Evidence ''

if (-not (Test-Path $BackendDir)) {
    Write-Evidence '  [ERROR] backend/ directory not found. Cannot run prisma migrate status.'
    $migrateOutput = '[ERROR] backend/ directory missing'
} else {
    try {
        # Run prisma migrate status from the backend directory
        $migrateOutput = & npx prisma migrate status 2>&1 | Out-String
        Write-Evidence $migrateOutput
    } catch {
        $migrateOutput = "[ERROR] npx prisma migrate status failed: $_"
        Write-Evidence "  [ERROR] $migrateOutput"
    }
}

# ---------------------------------------------------------------------------
# SECTION 4 — Backup Reminder
# ---------------------------------------------------------------------------
Write-EvidenceSection 'SECTION 4 — BACKUP REMINDER'
Write-Evidence "  Backup capture timestamp : $TimestampHuman"
Write-Evidence ''
Write-Evidence '  INSTRUCTIONS:'
Write-Evidence '  ─────────────'
Write-Evidence '  1. Confirm a verified database backup has been taken.'
Write-Evidence '     Use your backup tool (pg_dump, RDS snapshot, etc.) now.'
Write-Evidence ''
Write-Evidence '  2. Record the backup identifier in the space below:'
Write-Evidence ''
Write-Evidence '     Backup Identifier : ________________________________________'
Write-Evidence '     Backup Timestamp  : ________________________________________'
Write-Evidence '     Backup Confirmed  : [ ] Yes    [ ] No'
Write-Evidence ''
Write-Evidence '  3. Copy this identifier into PRODUCTION_CERT_TEMPLATE.md'
Write-Evidence '     Section 2 — Pre-Deployment Evidence before continuing.'

# ---------------------------------------------------------------------------
# SECTION 5 — Rollback Target
# ---------------------------------------------------------------------------
Write-EvidenceSection 'SECTION 5 — ROLLBACK TARGET'
Write-Evidence '  Rollback Tag    : v2026.07-skc-classification-certified'
Write-Evidence '  Rollback Commit : 4e1b8a9'
Write-Evidence ''
Write-Evidence '  To roll back application code:'
Write-Evidence '    git checkout v2026.07-skc-classification-certified'
Write-Evidence '    # OR'
Write-Evidence '    git checkout 4e1b8a9'
Write-Evidence ''
Write-Evidence '  To roll back the database migration (if migration was already applied):'
Write-Evidence '    npx prisma migrate resolve --rolled-back 20260729021810_skc_provenance'
Write-Evidence '    # Then restore from the backup identified in Section 4.'
Write-Evidence ''
Write-Evidence '  Estimated rollback window: < 15 minutes (excluding DB restore time).'

# ---------------------------------------------------------------------------
# SECTION 6 — Environment Variable Checklist
# ---------------------------------------------------------------------------
Write-EvidenceSection 'SECTION 6 — ENVIRONMENT VARIABLE CHECKLIST'
Write-Evidence '  Verify each variable is correctly set in the production environment.'
Write-Evidence '  Mark Y (present & correct) or N (missing / incorrect) in the cert template.'
Write-Evidence ''

$envVarsToCheck = @(
    'DATABASE_URL',
    'JWT_SECRET',
    'JWT_EXPIRES_IN',
    'NODE_ENV',
    'PORT',
    'NEXT_PUBLIC_API_URL'
)

$colName   = 'Variable'.PadRight(30)
$colStatus = 'Status in this shell'
Write-Evidence "  $colName  $colStatus"
Write-Evidence "  $('-' * 30)  $('-' * 25)"

foreach ($varName in $envVarsToCheck) {
    $val = [System.Environment]::GetEnvironmentVariable($varName)
    if ($null -ne $val -and $val -ne '') {
        # Mask secrets — show only first 4 chars
        $masked = if ($varName -in @('DATABASE_URL','JWT_SECRET')) {
            $val.Substring(0, [Math]::Min(4, $val.Length)) + '****** (masked)'
        } else {
            $val
        }
        $status = "SET   [$masked]"
    } else {
        $status = 'NOT SET in this shell (verify on production host)'
    }
    Write-Evidence "  $($varName.PadRight(30))  $status"
}

Write-Evidence ''
Write-Evidence '  NOTE: Variables shown as NOT SET here may still be set on the'
Write-Evidence '  production host or in Docker / systemd environment. Confirm'
Write-Evidence '  manually via: printenv <VAR> (Linux) or [System.Environment]::GetEnvironmentVariable (PS).'

# ---------------------------------------------------------------------------
# SECTION 7 — Next Steps
# ---------------------------------------------------------------------------
Write-EvidenceSection 'SECTION 7 — NEXT STEPS'
Write-Evidence '  Record the backup identifier below, then run migration.'
Write-Evidence ''
Write-Evidence '  Step A) Confirm backup ID is recorded in PRODUCTION_CERT_TEMPLATE.md.'
Write-Evidence '  Step B) Deploy application to target SHA: 4e1b8a9'
Write-Evidence '  Step C) Run database migration:'
Write-Evidence '          cd backend && npx prisma migrate deploy'
Write-Evidence '  Step D) Validate migration applied:'
Write-Evidence '          npx prisma migrate status'
Write-Evidence '  Step E) Run smoke tests:'
Write-Evidence '          .\scripts\production-smoke-test.ps1 -BaseUrl <URL> -AdminCookie <COOKIE> -TestRecordId <ID>'
Write-Evidence '  Step F) Complete post-deployment reconciliation SQL queries.'
Write-Evidence '  Step G) Fill in and sign PRODUCTION_CERT_TEMPLATE.md.'
Write-Evidence ''
Write-Evidence '  ──────────────────────────────────────────────────────────────────'
Write-Evidence '  OPERATOR: Record the backup identifier here before continuing:'
Write-Evidence ''
Write-Evidence '     Backup ID : _________________________________________________'
Write-Evidence ''
Write-Evidence '  Then proceed with migration.'
Write-Evidence '  ──────────────────────────────────────────────────────────────────'

# ---------------------------------------------------------------------------
# Write evidence file
# ---------------------------------------------------------------------------
Write-EvidenceSeparator
Write-Evidence "  Evidence file : $EvidenceFile"
Write-EvidenceSeparator

try {
    $evidenceLines | Out-File -FilePath $EvidenceFile -Encoding UTF8
    Write-Host ''
    Write-Host "✅  Evidence written to: $EvidenceFile" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] Failed to write evidence file: $_" -ForegroundColor Red
    exit 1
}

Write-Host ''
Write-Host '  Record the backup identifier below, then run migration.' -ForegroundColor Yellow
Write-Host ''
