#Requires -Version 5.1
<#
.SYNOPSIS
    Production Smoke Test Suite — SKC Classification Subsystem
    HCR Foundation Project

.DESCRIPTION
    Runs all 10 production smoke tests against a live deployment URL.
    Records PASS/FAIL for each test, writes a timestamped results file,
    and exits with code 0 (all pass) or 1 (any failure).

.PARAMETER BaseUrl
    Base URL of the production deployment, e.g. https://hcrf.example.com
    Do NOT include a trailing slash.

.PARAMETER TestRecordId
    The designated production test record ID (SkcStakeholderRegistration.id).
    This record MUST be pre-approved for smoke test classification in production.

.EXAMPLE
    $env:ADMIN_COOKIE="connect.sid=s%3A..."
    .\production-smoke-test.ps1 `
        -BaseUrl 'https://hcrf.example.com' `
        -TestRecordId 'clxxxxxxxxxxxxxxxx'

.PARAMETER TestRecordId
    The designated production test record ID (SkcStakeholderRegistration.id).
    This record MUST be pre-approved for smoke test classification in production.

.EXAMPLE
    .\production-smoke-test.ps1 `
        -BaseUrl 'https://hcrf.example.com' `
        -AdminCookie 'connect.sid=s%3Axxx' `
        -NonAdminCookie 'connect.sid=s%3Ayyy' `
        -TestRecordId 'clxxxxxxxxxxxxxxxx'

.NOTES
    Generated by: scripts/production-smoke-test.ps1
    Subsystem   : SKC Classification
    Release tag : v2026.07-skc-production-ready
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$BaseUrl,

    [Parameter(Mandatory = $true)]
    [string]$TestRecordId
)

$AdminCookie = $env:ADMIN_COOKIE
if (-not $AdminCookie) {
    Write-Host "Please enter Admin Cookie (hidden): " -NoNewline
    $sec = Read-Host -AsSecureString
    $AdminCookie = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
}

$NonAdminCookie = $env:NON_ADMIN_COOKIE

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'   # We handle errors per-test

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
$resultLines  = [System.Collections.Generic.List[string]]::new()
$testResults  = [System.Collections.Generic.List[hashtable]]::new()
$Timestamp    = Get-Date -Format 'yyyyMMdd_HHmmss'
$StartTime    = Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'

$ScriptDir    = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot  = Split-Path -Parent $ScriptDir
$ResultsFile  = Join-Path $ProjectRoot "smoke-test-results-$Timestamp.txt"

function Log {
    param([string]$Line = '')
    Write-Host $Line
    $resultLines.Add($Line)
}

function LogSeparator { Log ('─' * 72) }

function New-Uuid { return [System.Guid]::NewGuid().ToString() }

function Invoke-ApiRequest {
    param(
        [string]$Method,
        [string]$Url,
        [hashtable]$Headers = @{},
        [object]$Body = $null,
        [string]$ContentType = 'application/json'
    )

    $iwrParams = @{
        Method             = $Method
        Uri                = $Url
        Headers            = $Headers
        SkipCertificateCheck = $true
        UseBasicParsing    = $true
        ErrorAction        = 'Stop'
    }

    if ($null -ne $Body) {
        $iwrParams['Body']        = ($Body | ConvertTo-Json -Depth 10 -Compress)
        $iwrParams['ContentType'] = $ContentType
    }

    try {
        $response = Invoke-WebRequest @iwrParams
        return @{
            StatusCode = [int]$response.StatusCode
            Body       = $response.Content
            Error      = $null
            Response   = $response
        }
    } catch [System.Net.WebException] {
        $sc = [int]$_.Exception.Response.StatusCode
        $body = ''
        try {
            $reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
            $body = $reader.ReadToEnd()
        } catch {}
        return @{
            StatusCode = $sc
            Body       = $body
            Error      = $_.Exception.Message
            Response   = $null
        }
    } catch {
        return @{
            StatusCode = 0
            Body       = ''
            Error      = $_.Exception.Message
            Response   = $null
        }
    }
}

function Record-TestResult {
    param(
        [int]    $TestNum,
        [string] $TestName,
        [string] $Expected,
        [int]    $ActualStatus,
        [bool]   $Passed,
        [string] $Notes = ''
    )

    $ts     = Get-Date -Format 'HH:mm:ss'
    $result = if ($Passed) { 'PASS' } else { 'FAIL' }
    $color  = if ($Passed) { 'Green' } else { 'Red' }
    $line   = "  [$result] Test $($TestNum.ToString().PadLeft(2,'0')): $TestName"
    $detail = "           Expected: $Expected | Actual status: $ActualStatus | $ts"

    Write-Host $line -ForegroundColor $color
    Write-Host $detail
    if ($Notes) { Write-Host "           Notes: $Notes" -ForegroundColor Gray }
    Log $line
    Log $detail
    if ($Notes) { Log "           Notes: $Notes" }

    $testResults.Add(@{
        Num      = $TestNum
        Name     = $TestName
        Expected = $Expected
        Actual   = $ActualStatus
        Passed   = $Passed
        Notes    = $Notes
    })
}

# ---------------------------------------------------------------------------
# HEADER
# ---------------------------------------------------------------------------
Log ('=' * 72)
Log '  HCR FOUNDATION — SKC CLASSIFICATION SUBSYSTEM'
Log '  PRODUCTION SMOKE TEST SUITE'
Log "  Base URL     : $BaseUrl"
Log "  Test Record  : $TestRecordId"
Log "  Started      : $StartTime"
Log ('=' * 72)
Log ''

# ---------------------------------------------------------------------------
# Pre-flight: generate shared idempotency key (used for Tests 6 & 8)
# ---------------------------------------------------------------------------
$SharedIdempotencyKey = New-Uuid
$previewToken         = $null   # will be populated by Test 5

Log "  [INFO] Shared idempotency key for Tests 6 & 8 : $SharedIdempotencyKey"
Log ''

# ---------------------------------------------------------------------------
# TEST 1 — Anonymous access → expect 401
# ---------------------------------------------------------------------------
LogSeparator
Log '  TEST 01: Anonymous GET /api/admin/skc/classification/queue → expect 401'
LogSeparator

$r1 = Invoke-ApiRequest -Method 'GET' -Url "$BaseUrl/api/admin/skc/classification/queue"
$pass1 = ($r1.StatusCode -eq 401)
Record-TestResult -TestNum 1 `
    -TestName 'Anonymous queue access → 401' `
    -Expected '401 Unauthorized' `
    -ActualStatus $r1.StatusCode `
    -Passed $pass1 `
    -Notes $(if ($r1.Error) { "Error: $($r1.Error)" } else { '' })

# ---------------------------------------------------------------------------
# TEST 2 — Non-admin authenticated access → expect 403
# ---------------------------------------------------------------------------
LogSeparator
Log '  TEST 02: Non-admin GET /api/admin/skc/classification/queue → expect 403'
LogSeparator

if ($NonAdminCookie -eq '') {
    Log '  [WARNING] NonAdminCookie not provided — skipping Test 2.'
    Record-TestResult -TestNum 2 `
        -TestName 'Non-admin queue access → 403' `
        -Expected '403 Forbidden' `
        -ActualStatus 0 `
        -Passed $false `
        -Notes 'SKIPPED: NonAdminCookie parameter not provided'
} else {
    $r2 = Invoke-ApiRequest -Method 'GET' `
        -Url "$BaseUrl/api/admin/skc/classification/queue" `
        -Headers @{ Cookie = $NonAdminCookie }
    $pass2 = ($r2.StatusCode -eq 403)
    Record-TestResult -TestNum 2 `
        -TestName 'Non-admin queue access → 403' `
        -Expected '403 Forbidden' `
        -ActualStatus $r2.StatusCode `
        -Passed $pass2 `
        -Notes $(if ($r2.Error) { "Error: $($r2.Error)" } else { '' })
}

# ---------------------------------------------------------------------------
# TEST 3 — Admin access → expect 200 with 'records' in body
# ---------------------------------------------------------------------------
LogSeparator
Log '  TEST 03: Admin GET /api/admin/skc/classification/queue → expect 200 + records'
LogSeparator

$r3 = Invoke-ApiRequest -Method 'GET' `
    -Url "$BaseUrl/api/admin/skc/classification/queue" `
    -Headers @{ Cookie = $AdminCookie }

$bodyHasRecords = ($r3.Body -match '"records"')
$pass3 = ($r3.StatusCode -eq 200) -and $bodyHasRecords
Record-TestResult -TestNum 3 `
    -TestName 'Admin queue access → 200 + records' `
    -Expected '200 with body containing "records"' `
    -ActualStatus $r3.StatusCode `
    -Passed $pass3 `
    -Notes $(if (-not $bodyHasRecords -and $r3.StatusCode -eq 200) { 'Body did not contain "records"' } elseif ($r3.Error) { "Error: $($r3.Error)" } else { '' })

# ---------------------------------------------------------------------------
# TEST 4 — Admin access with provenance filter → expect 200
# ---------------------------------------------------------------------------
LogSeparator
Log '  TEST 04: Admin GET /api/admin/skc/classification/queue?provenance=UNKNOWN → expect 200'
LogSeparator

$r4 = Invoke-ApiRequest -Method 'GET' `
    -Url "$BaseUrl/api/admin/skc/classification/queue?provenance=UNKNOWN" `
    -Headers @{ Cookie = $AdminCookie }

$pass4 = ($r4.StatusCode -eq 200)
Record-TestResult -TestNum 4 `
    -TestName 'Admin queue with provenance filter → 200' `
    -Expected '200 OK' `
    -ActualStatus $r4.StatusCode `
    -Passed $pass4 `
    -Notes $(if ($r4.Error) { "Error: $($r4.Error)" } else { '' })

# ---------------------------------------------------------------------------
# TEST 5 — Preview classification → expect 200 with previewToken
# ---------------------------------------------------------------------------
LogSeparator
Log '  TEST 05: Admin POST /api/admin/skc/classification/preview → expect 200 + previewToken'
LogSeparator

$previewBody = @{
    entityType       = 'SKC_STAKEHOLDER_REGISTRATION'
    recordIds        = @($TestRecordId)
    targetProvenance = 'PRODUCTION'
}

$r5 = Invoke-ApiRequest -Method 'POST' `
    -Url "$BaseUrl/api/admin/skc/classification/preview" `
    -Headers @{ Cookie = $AdminCookie } `
    -Body $previewBody

$bodyHasToken = $false
if ($r5.StatusCode -eq 200 -and $r5.Body) {
    try {
        $parsed5 = $r5.Body | ConvertFrom-Json
        if ($parsed5.previewToken) {
            $previewToken = $parsed5.previewToken
            $bodyHasToken = $true
        }
    } catch {}
}

$pass5 = ($r5.StatusCode -eq 200) -and $bodyHasToken
Record-TestResult -TestNum 5 `
    -TestName 'Preview classification → 200 + previewToken' `
    -Expected '200 with previewToken in response' `
    -ActualStatus $r5.StatusCode `
    -Passed $pass5 `
    -Notes $(
        if ($pass5) { "previewToken captured: $($previewToken.Substring(0,[Math]::Min(8,$previewToken.Length)))..." }
        elseif ($r5.StatusCode -eq 200 -and -not $bodyHasToken) { 'No previewToken in response body' }
        elseif ($r5.Error) { "Error: $($r5.Error)" }
        else { '' }
    )

# ---------------------------------------------------------------------------
# TEST 6 — Apply classification (first time) → expect 200 + classifiedCount >= 0
# ---------------------------------------------------------------------------
LogSeparator
Log '  TEST 06: Admin PATCH /api/admin/skc/classification → expect 200 + classifiedCount >= 0'
LogSeparator

$classifiedCount6 = -1
if ($null -eq $previewToken -or $previewToken -eq '') {
    Log '  [WARNING] previewToken not available (Test 5 failed) — skipping Test 6.'
    Record-TestResult -TestNum 6 `
        -TestName 'Apply classification (first) → 200 + classifiedCount >= 0' `
        -Expected '200 with classifiedCount >= 0' `
        -ActualStatus 0 `
        -Passed $false `
        -Notes 'SKIPPED: previewToken from Test 5 not available'
} else {
    $patchBody6 = @{
        previewToken    = $previewToken
        idempotencyKey  = $SharedIdempotencyKey
        reason          = 'Production deployment smoke test - authorized test record'
    }

    $r6 = Invoke-ApiRequest -Method 'PATCH' `
        -Url "$BaseUrl/api/admin/skc/classification" `
        -Headers @{ Cookie = $AdminCookie } `
        -Body $patchBody6

    $pass6 = $false
    if ($r6.StatusCode -eq 200 -and $r6.Body) {
        try {
            $parsed6 = $r6.Body | ConvertFrom-Json
            if ($null -ne $parsed6.classifiedCount -and [int]$parsed6.classifiedCount -ge 0) {
                $classifiedCount6 = [int]$parsed6.classifiedCount
                $pass6 = $true
            }
        } catch {}
    }

    Record-TestResult -TestNum 6 `
        -TestName 'Apply classification (first) → 200 + classifiedCount >= 0' `
        -Expected '200 with classifiedCount >= 0' `
        -ActualStatus $r6.StatusCode `
        -Passed $pass6 `
        -Notes $(
            if ($pass6) { "classifiedCount: $classifiedCount6" }
            elseif ($r6.StatusCode -eq 200) { 'classifiedCount missing or < 0 in response' }
            elseif ($r6.Error) { "Error: $($r6.Error)" }
            else { '' }
        )
}

# ---------------------------------------------------------------------------
# TEST 7 — Classification history for test record → expect 200 with >= 1 record
# ---------------------------------------------------------------------------
LogSeparator
Log "  TEST 07: GET /api/admin/skc/classification/history?recordId=$TestRecordId → expect 200 + >= 1 record"
LogSeparator

$r7 = Invoke-ApiRequest -Method 'GET' `
    -Url "$BaseUrl/api/admin/skc/classification/history?recordId=$TestRecordId" `
    -Headers @{ Cookie = $AdminCookie }

$pass7 = $false
if ($r7.StatusCode -eq 200 -and $r7.Body) {
    try {
        $parsed7 = $r7.Body | ConvertFrom-Json
        # Accept either an array or an object with records/data/history property
        if ($parsed7 -is [System.Array] -and $parsed7.Count -ge 1) {
            $pass7 = $true
        } elseif ($parsed7.records -and $parsed7.records.Count -ge 1) {
            $pass7 = $true
        } elseif ($parsed7.data -and $parsed7.data.Count -ge 1) {
            $pass7 = $true
        } elseif ($parsed7.history -and $parsed7.history.Count -ge 1) {
            $pass7 = $true
        } elseif ($parsed7.total -and [int]$parsed7.total -ge 1) {
            $pass7 = $true
        }
    } catch {}
}

Record-TestResult -TestNum 7 `
    -TestName 'Classification history for test record → 200 + >= 1 record' `
    -Expected '200 with at least one history record' `
    -ActualStatus $r7.StatusCode `
    -Passed $pass7 `
    -Notes $(if ($r7.Error) { "Error: $($r7.Error)" } elseif ($r7.StatusCode -eq 200 -and -not $pass7) { 'Response did not contain at least 1 history record' } else { '' })

# ---------------------------------------------------------------------------
# TEST 8 — Idempotent PATCH (same idempotencyKey) → expect 200 + idempotent:true
# ---------------------------------------------------------------------------
LogSeparator
Log '  TEST 08: Repeat PATCH with same idempotencyKey → expect 200 + idempotent:true'
LogSeparator

if ($null -eq $previewToken -or $previewToken -eq '') {
    Log '  [WARNING] previewToken not available — skipping Test 8.'
    Record-TestResult -TestNum 8 `
        -TestName 'Idempotent re-apply (same idempotencyKey) → 200 + idempotent:true' `
        -Expected '200 with idempotent:true' `
        -ActualStatus 0 `
        -Passed $false `
        -Notes 'SKIPPED: previewToken not available'
} else {
    # Request a new preview token for the idempotent call (same idempotencyKey)
    $previewBody8 = @{
        entityType       = 'SKC_STAKEHOLDER_REGISTRATION'
        recordIds        = @($TestRecordId)
        targetProvenance = 'PRODUCTION'
    }
    $r8preview = Invoke-ApiRequest -Method 'POST' `
        -Url "$BaseUrl/api/admin/skc/classification/preview" `
        -Headers @{ Cookie = $AdminCookie } `
        -Body $previewBody8

    $previewToken8 = $null
    if ($r8preview.StatusCode -eq 200 -and $r8preview.Body) {
        try {
            $parsed8p = $r8preview.Body | ConvertFrom-Json
            $previewToken8 = $parsed8p.previewToken
        } catch {}
    }

    $patchBody8 = @{
        previewToken   = if ($previewToken8) { $previewToken8 } else { $previewToken }
        idempotencyKey = $SharedIdempotencyKey   # SAME key as Test 6
        reason         = 'Production deployment smoke test - authorized test record'
    }

    $r8 = Invoke-ApiRequest -Method 'PATCH' `
        -Url "$BaseUrl/api/admin/skc/classification" `
        -Headers @{ Cookie = $AdminCookie } `
        -Body $patchBody8

    $pass8 = $false
    if ($r8.StatusCode -eq 200 -and $r8.Body) {
        try {
            $parsed8 = $r8.Body | ConvertFrom-Json
            if ($parsed8.idempotent -eq $true) { $pass8 = $true }
        } catch {}
    }

    Record-TestResult -TestNum 8 `
        -TestName 'Idempotent re-apply (same idempotencyKey) → 200 + idempotent:true' `
        -Expected '200 with idempotent:true' `
        -ActualStatus $r8.StatusCode `
        -Passed $pass8 `
        -Notes $(
            if ($r8.StatusCode -eq 200 -and -not $pass8) { 'idempotent flag not true in response' }
            elseif ($r8.Error) { "Error: $($r8.Error)" }
            else { '' }
        )
}

# ---------------------------------------------------------------------------
# TEST 9 — Preview for already-PRODUCTION record → expect blockedCount = 1
# ---------------------------------------------------------------------------
LogSeparator
Log '  TEST 09: Preview PRODUCTION→PRODUCTION transition → expect 200 + blockedCount = 1'
LogSeparator

$previewBody9 = @{
    entityType       = 'SKC_STAKEHOLDER_REGISTRATION'
    recordIds        = @($TestRecordId)
    targetProvenance = 'PRODUCTION'
}

$r9 = Invoke-ApiRequest -Method 'POST' `
    -Url "$BaseUrl/api/admin/skc/classification/preview" `
    -Headers @{ Cookie = $AdminCookie } `
    -Body $previewBody9

$pass9 = $false
$blockedCount9 = 'N/A'
if ($r9.StatusCode -eq 200 -and $r9.Body) {
    try {
        $parsed9 = $r9.Body | ConvertFrom-Json
        if ($null -ne $parsed9.blockedCount -and [int]$parsed9.blockedCount -eq 1) {
            $pass9 = $true
            $blockedCount9 = 1
        } elseif ($null -ne $parsed9.blocked -and $parsed9.blocked.Count -eq 1) {
            $pass9 = $true
            $blockedCount9 = 1
        }
    } catch {}
}

Record-TestResult -TestNum 9 `
    -TestName 'Preview PRODUCTION→PRODUCTION → 200 + blockedCount = 1' `
    -Expected '200 with blockedCount = 1 (PRODUCTION→PRODUCTION not allowed)' `
    -ActualStatus $r9.StatusCode `
    -Passed $pass9 `
    -Notes $(
        if ($r9.StatusCode -eq 200 -and -not $pass9) { "blockedCount was $blockedCount9 (expected 1)" }
        elseif ($r9.Error) { "Error: $($r9.Error)" }
        else { "blockedCount = $blockedCount9 (transition correctly blocked)" }
    )

# ---------------------------------------------------------------------------
# TEST 10 — History (no filter) → expect 200 + total > 0
# ---------------------------------------------------------------------------
LogSeparator
Log '  TEST 10: Admin GET /api/admin/skc/classification/history (no filter) → expect 200 + total > 0'
LogSeparator

$r10 = Invoke-ApiRequest -Method 'GET' `
    -Url "$BaseUrl/api/admin/skc/classification/history" `
    -Headers @{ Cookie = $AdminCookie }

$pass10 = $false
$total10 = 0
if ($r10.StatusCode -eq 200 -and $r10.Body) {
    try {
        $parsed10 = $r10.Body | ConvertFrom-Json
        if ($parsed10 -is [System.Array] -and $parsed10.Count -gt 0) {
            $pass10 = $true
            $total10 = $parsed10.Count
        } elseif ($null -ne $parsed10.total -and [int]$parsed10.total -gt 0) {
            $pass10 = $true
            $total10 = [int]$parsed10.total
        } elseif ($parsed10.records -and $parsed10.records.Count -gt 0) {
            $pass10 = $true
            $total10 = $parsed10.records.Count
        } elseif ($parsed10.data -and $parsed10.data.Count -gt 0) {
            $pass10 = $true
            $total10 = $parsed10.data.Count
        }
    } catch {}
}

Record-TestResult -TestNum 10 `
    -TestName 'History (no filter) → 200 + total > 0' `
    -Expected '200 with total > 0' `
    -ActualStatus $r10.StatusCode `
    -Passed $pass10 `
    -Notes $(
        if ($pass10) { "total/count: $total10" }
        elseif ($r10.StatusCode -eq 200) { 'Could not determine total from response' }
        elseif ($r10.Error) { "Error: $($r10.Error)" }
        else { '' }
    )

# ---------------------------------------------------------------------------
# SUMMARY
# ---------------------------------------------------------------------------
$passed = ($testResults | Where-Object { $_.Passed }).Count
$failed = ($testResults | Where-Object { -not $_.Passed }).Count
$total  = $testResults.Count

Log ''
Log ('=' * 72)
Log '  SMOKE TEST SUMMARY'
Log ('=' * 72)
Log "  Total  : $total"
Log "  Passed : $passed" 
Log "  Failed : $failed"
Log ''

# Summary table
Log ("  {0,-4} {1,-52} {2,-6} {3}" -f 'Test', 'Name', 'Status', 'Result')
Log ("  {0,-4} {1,-52} {2,-6} {3}" -f '────', ('─' * 52), '──────', '──────')
foreach ($tr in $testResults) {
    $res = if ($tr.Passed) { 'PASS' } else { 'FAIL' }
    Log ("  {0,-4} {1,-52} {2,-6} {3}" -f $tr.Num, $tr.Name.Substring(0,[Math]::Min(52,$tr.Name.Length)), $tr.Actual, $res)
}

Log ''
$endTime = Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'
Log "  Completed : $endTime"
Log "  Results file : $ResultsFile"
Log ('=' * 72)

# Print to console with color
if ($failed -eq 0) {
    Write-Host ''
    Write-Host "✅  ALL $total SMOKE TESTS PASSED" -ForegroundColor Green
} else {
    Write-Host ''
    Write-Host "❌  $failed OF $total SMOKE TESTS FAILED" -ForegroundColor Red
    Write-Host '    Review results file for details.' -ForegroundColor Red
}

# ---------------------------------------------------------------------------
# Write results file
# ---------------------------------------------------------------------------
try {
    $resultLines | Out-File -FilePath $ResultsFile -Encoding UTF8
    Write-Host "📄  Results written to: $ResultsFile" -ForegroundColor Cyan
} catch {
    Write-Host "[ERROR] Failed to write results file: $_" -ForegroundColor Red
}

# ---------------------------------------------------------------------------
# Exit code
# ---------------------------------------------------------------------------
if ($failed -gt 0) {
    exit 1
} else {
    exit 0
}
