import { PERMISSIONS } from './permissions.js';

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SYSTEM_ADMIN: ["*"],
  ADMIN: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.MEMBERSHIP_VIEW,
    PERMISSIONS.MEMBERSHIP_REVIEW,
    PERMISSIONS.MEMBERSHIP_APPROVE,
    
    PERMISSIONS.MAGAZINE_VIEW,
    PERMISSIONS.MAGAZINE_CREATE,
    PERMISSIONS.MAGAZINE_EDIT,
    PERMISSIONS.MAGAZINE_REVIEW,
    PERMISSIONS.MAGAZINE_PUBLISH,
    PERMISSIONS.MAGAZINE_ARCHIVE,
    PERMISSIONS.MAGAZINE_DELETE,

    PERMISSIONS.MASTER_ARTISANS_VIEW,
    PERMISSIONS.MASTER_ARTISANS_CREATE,
    PERMISSIONS.MASTER_ARTISANS_EDIT,
    PERMISSIONS.MASTER_ARTISANS_REVIEW,
    PERMISSIONS.MASTER_ARTISANS_PUBLISH,
    PERMISSIONS.MASTER_ARTISANS_DELETE,

    PERMISSIONS.SKC_EVIDENCE_REVIEW,
    PERMISSIONS.SKC_HEARINGS_MANAGE,
    PERMISSIONS.SKC_VALIDATION_REVIEW,
    PERMISSIONS.SKC_EXPERT_REVIEW,
    PERMISSIONS.SKC_LIFECYCLE_MANAGE,
    PERMISSIONS.SKC_CONFIG_MANAGE,
    PERMISSIONS.SKC_STAKEHOLDERS_MANAGE,

    PERMISSIONS.PUBLICATIONS_VIEW,
    PERMISSIONS.PUBLICATIONS_CREATE,
    PERMISSIONS.PUBLICATIONS_EDIT,
    PERMISSIONS.PUBLICATIONS_REVIEW,
    PERMISSIONS.PUBLICATIONS_PUBLISH,
    PERMISSIONS.PUBLICATIONS_DELETE,
  ],
  OPERATIONS_MANAGER: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.MEMBERSHIP_VIEW,
    PERMISSIONS.MEMBERSHIP_REVIEW,
  ],

  // Publications & Magazine
  MAGAZINE_EDITOR: [
    PERMISSIONS.MAGAZINE_VIEW,
    PERMISSIONS.MAGAZINE_CREATE,
    PERMISSIONS.MAGAZINE_EDIT,
    PERMISSIONS.MAGAZINE_PUBLISH,
    PERMISSIONS.MAGAZINE_ARCHIVE,
  ],
  EDITORIAL_REVIEWER: [
    PERMISSIONS.MAGAZINE_VIEW,
    PERMISSIONS.MAGAZINE_REVIEW,
    PERMISSIONS.PUBLICATIONS_VIEW,
    PERMISSIONS.PUBLICATIONS_REVIEW,
  ],
  PUBLICATIONS_EDITOR: [
    PERMISSIONS.PUBLICATIONS_VIEW,
    PERMISSIONS.PUBLICATIONS_CREATE,
    PERMISSIONS.PUBLICATIONS_EDIT,
    PERMISSIONS.PUBLICATIONS_PUBLISH,
  ],

  // Membership
  MEMBERSHIP_MODERATOR: [
    PERMISSIONS.MEMBERSHIP_VIEW,
    PERMISSIONS.MEMBERSHIP_REVIEW,
    PERMISSIONS.MEMBERSHIP_APPROVE,
  ],
  MEMBERSHIP_REVIEWER: [
    PERMISSIONS.MEMBERSHIP_VIEW,
    PERMISSIONS.MEMBERSHIP_REVIEW,
  ],

  // Master Artisans
  MASTER_ARTISAN_MODERATOR: [
    PERMISSIONS.MASTER_ARTISANS_VIEW,
    PERMISSIONS.MASTER_ARTISANS_CREATE,
    PERMISSIONS.MASTER_ARTISANS_EDIT,
    PERMISSIONS.MASTER_ARTISANS_PUBLISH,
  ],
  MASTER_ARTISAN_REVIEWER: [
    PERMISSIONS.MASTER_ARTISANS_VIEW,
    PERMISSIONS.MASTER_ARTISANS_REVIEW,
  ],
  NOMINATION_REVIEWER: [
    PERMISSIONS.MASTER_ARTISANS_VIEW,
    PERMISSIONS.MASTER_ARTISANS_REVIEW,
  ],

  // SKC
  ASSESSMENT_ADMINISTRATOR: [
    PERMISSIONS.SKC_LIFECYCLE_MANAGE,
    PERMISSIONS.SKC_CONFIG_MANAGE,
    PERMISSIONS.SKC_STAKEHOLDERS_MANAGE,
    PERMISSIONS.SKC_HEARINGS_MANAGE,
  ],
  EVIDENCE_REVIEWER: [
    PERMISSIONS.SKC_EVIDENCE_REVIEW,
  ],
  PUBLIC_HEARING_MODERATOR: [
    PERMISSIONS.SKC_HEARINGS_MANAGE,
  ],
  VALIDATION_REVIEWER: [
    PERMISSIONS.SKC_VALIDATION_REVIEW,
  ],
  EXPERT_REVIEWER: [
    PERMISSIONS.SKC_EXPERT_REVIEW,
  ],
};
