import { GlossaryEntry, GlossaryType, FieldValidationStatus } from './data';

const parseTools = (dataArray: string[]): GlossaryEntry[] => {
  return dataArray.map(line => {
    const parts = line.split('|');
    return {
      term: parts[0],
      localSpellingVariants: parts[1] || undefined,
      type: 'Tool' as GlossaryType,
      craftCategory: parts[2],
      definition: parts[3],
      traditionalUsage: '',
      technicalMeaning: '',
      relatedTerms: [],
      exampleUsage: '',
      material: parts[4],
      whoUsesIt: parts[5],
      relatedTechnique: parts[6],
      validationStatus: (parts[7] || 'Requires Field Validation') as FieldValidationStatus,
      sourceType: parts[8] || 'Online Evidence',
    };
  });
};

const rawTools = [
  // Textile & Shawl Tools
  "Kani|Tujli|Kani Shawls|Small wooden bobbin or stick used to carry colored weft yarn|Wood|Masterweaver|Discontinuous Weft Weaving|Verified|PureKashmir",
  "Handloom|Khaddi|Pashmina Weaving|Holds warp threads for weaving|Timber|Weaver|Weaving|Verified|Field Knowledge",
  "Spinning Wheel|Yinder|Pashmina|Traditional wheel used for drafting and spinning|Wood|Spinner|Spinning|Verified|Traditional",
  "Spindle|Pech|Pashmina|Twists raw fiber into yarn|Wood|Spinner|Spinning|Requires Field Validation|General Knowledge",
  "Shuttle|Khoki|Shawl|Passes the thick foundation weft|Wood|Weaver|Weaving|Requires Field Validation|General Knowledge",
  "Warp Beam|Tann|Shawl|Holds and supplies warp yarn under tension|Timber|Weaver|Loom Setup|Requires Field Validation|General Knowledge",
  "Reed|Phani|Shawl|Separates warp threads and beats weft|Bamboo / Steel|Weaver|Beating|Requires Field Validation|General Knowledge",
  "Heddle|Saaz|Shawl|Lifts warp threads to create the shed|Cord|Weaver|Shedding|Requires Field Validation|General Knowledge",
  "Yarn Winder|Pretch|Shawl|Winds spun yarn onto bobbins|Wood|Assistant|Winding|Requires Field Validation|General Knowledge",
  "Measuring Rod|Gaz|Shawl|Measures the length of the woven textile|Wood|Merchant|Measurement|Requires Field Validation|General Knowledge",
  "Loom Frame|Waan|Shawl|Structural body of the weaving apparatus|Wood|Weaver|Loom Assembly|Requires Field Validation|General Knowledge",
  "Tension Pegs|Kil|Shawl|Maintains strict tension on the warp|Wood|Weaver|Tensioning|Requires Field Validation|General Knowledge",
  "Treadles|Paai-choob|Shawl|Foot pedals used to operate heddles|Wood|Weaver|Shedding|Requires Field Validation|General Knowledge",
  "Harness|Jala|Shawl|Lifts specific groups of warp for patterns|Cord|Masterweaver|Patterning|Historical / Archival|Archival",
  "Bobbin Winder|Charkhi|Shawl|Transfers yarn to shuttles|Wood / Metal|Assistant|Prep|Requires Field Validation|General Knowledge",
  "Shed Stick|Golla|Shawl|Keeps the warp layers separated|Wood|Weaver|Shedding|Requires Field Validation|General Knowledge",
  "Drawing Hook|Aankuz|Shawl|Pulls warp threads through the reed|Metal|Weaver|Threading|Requires Field Validation|General Knowledge",
  "Pouncing Pad|Pounce|Shawl|Transfers patterns for printing|Cloth|Printer|Transfer|Requires Field Validation|General Knowledge",
  "Washing Vat|Vat|Shawl|Soaks raw Pashm|Copper / Clay|Dhobi|Washing|Requires Field Validation|General Knowledge",
  "Teasing Burr|Xanthium|Shawl|Raises the nap on heavy woolen blankets|Plant Burr|Finisher|Teasing|Historical / Archival|Archival",

  // Embroidery Tools
  "Aari Hook|Aari Hook|Crewel / Namda / Chain Stitch|Hooked needle for chain stitch embroidery|Steel|Ari-Kash|Chain Stitch / Zalakdozi|Verified|PureKashmir / Trade",
  "Wooden Frame|Adda|Embroidery|Wooden frame used to stretch fabric|Wood / Cloth|Embroiderer|Tensioning|Verified|PureKashmir / Trade",
  "Sozni Needle|Sozan|Sozni|Executes microscopic stitches on Pashmina|Steel|Sozni-Kash|Satin / Stem Stitch|Verified|Trade Usage",
  "Pattern Sheet|Naksha / Naqash Pattern|Embroidery / Papier Mâché|Design drawing or pattern guide|Paper|Naqash|Design|Verified|PureKashmir",
  "Tracing Paper|Khakha|Embroidery|Holds the perforated design for transfer|Paper|Naqash|Transfer|Verified|Trade Usage",
  "Thimble|Top|Embroidery|Protections for artisan's finger|Brass|Embroiderer|Needlework|Requires Field Validation|General Knowledge",
  "Scissors|Mekraz|Embroidery / Carpet / Textile|Trimming and finishing|Steel|Embroiderer|Trimming|Verified|Gaatha",
  "Thread Reel|Phiki|Embroidery|Holds silk or cotton thread|Wood|Embroiderer|Management|Requires Field Validation|General Knowledge",
  "Needle Case|Sozan-Daan|Embroidery|Stores fine needles|Wood|Embroiderer|Storage|Requires Field Validation|General Knowledge",
  "Embroidery Hoop|Chamb|Embroidery|Small portable tension frame|Wood|Embroiderer|Tensioning|Requires Field Validation|General Knowledge",
  "Pricking Pin|Sozan-e-Khakha|Embroidery|Punches holes in tracing paper|Steel|Naqash|Prep|Requires Field Validation|General Knowledge",
  "Pounce Bag|Potli|Embroidery|Applies charcoal dust through Khakha|Cloth|Naqash|Transfer|Verified|Trade Usage",
  "Charcoal Box|Surma-Daan|Embroidery|Stores indigo/charcoal powder|Wood|Naqash|Transfer|Requires Field Validation|General Knowledge",
  "Tracing Wheel|Gargari|Embroidery|Perforates thick paper|Metal|Naqash|Drafting|Requires Field Validation|General Knowledge",
  "Tension Straps|Tann-e-Adda|Embroidery|Secures fabric to Adda|Canvas|Embroiderer|Framing|Requires Field Validation|General Knowledge",
  "Stiletto|Tchok|Embroidery|Pierces fabric for eyelet work|Bone|Embroiderer|Cutwork|Requires Field Validation|General Knowledge",
  "Iron|Istari|Embroidery|Presses finished embroidery flat|Iron|Presser|Finishing|Verified|Trade Usage",
  "Namda Mat|Wagoo|Namda|Straw mat used to roll felt|Reed|Felter|Felting|Historical / Archival|Archival",
  "Felting Soap|Sabun|Namda|Alkalized soap for matting wool|Soap|Felter|Felting|Requires Field Validation|General Knowledge",
  "Gabba Hook|Ari-Gabba|Gabba|Heavy hooked needle for recycled blankets|Steel|Ari-Kash|Applique|Requires Field Validation|General Knowledge",

  // Carpet Weaving Tools
  "Carpet Loom|Waan|Carpet Weaving|Holds warp threads for weaving|Timber / Steel|Kalimba|Weaving|Verified|PureKashmir / Trade",
  "Spiral Blade|Khur|Carpet Weaving|Spiral blade used to cut thread after knotting|Steel|Kalimba|Knotting|Verified|Gaatha",
  "Comb Beater|Panja|Carpet Weaving|Wooden or metal comb used to compact knots|Metal / Wood|Kalimba|Compression|Verified|Gaatha",
  "Talim Sheet|Talim / Taleem Sheet|Kani / Carpet|Coded instruction sheet read by weavers|Paper|Kalimba|Pattern Reading|Verified|PureKashmir / Local Sources",
  "Carpet Scissors|Kainchi|Carpet Weaving|Shears the carpet pile to a uniform height|Specialized Steel|Kalimba|Shearing|Verified|Gaatha",
  "Warp Separator|Golla|Carpet Weaving|Maintains space between front and back warps|Wood|Kalimba|Warp Management|Requires Field Validation|General Knowledge",
  "Measuring Scale|Gaz|Carpet Weaving|Ensures knot density|Brass|Masterweaver|Quality Control|Requires Field Validation|General Knowledge",
  "Yarn Basket|Tokri|Carpet Weaving|Holds pre-cut yarn balls|Willow|Kalimba|Storage|Requires Field Validation|General Knowledge",
  "Warp Tensioner|Pech|Carpet Weaving|Tightens the warp beam|Metal|Masterweaver|Tensioning|Requires Field Validation|General Knowledge",
  "Talim Stand|Talim-Daan|Carpet Weaving|Holds the Talim at eye level|Wood|Kalimba|Reading|Requires Field Validation|General Knowledge",
  "Weaver's Bench|Takht|Carpet Weaving|Plank where weavers sit|Wood|Kalimba|Ergonomics|Requires Field Validation|General Knowledge",
  "Selvedge Hook|Kunda|Carpet Weaving|Maintains tension on edges|Iron|Kalimba|Edge Binding|Requires Field Validation|General Knowledge",
  "Iron Beater|Loh-Daftun|Carpet Weaving|Heavier beater for silk carpets|Iron|Kalimba|Compression|Requires Field Validation|General Knowledge",
  "Shed Roller|Charkhi|Carpet Weaving|Reverses shed for return weft|Wood|Kalimba|Shedding|Requires Field Validation|General Knowledge",
  "Fluff Brush|Moee|Carpet Weaving|Brushes out loose fluff|Bristle|Kalimba|Finishing|Requires Field Validation|General Knowledge",
  "Graph Paper|Naksha|Carpet Weaving|Design drawing or pattern guide|Paper|Talim-Writer|Drafting|Verified|PureKashmir",
  "Backing Beam|Pust-Tann|Carpet Weaving|Lower beam holding finished rug|Timber|Kalimba|Structure|Requires Field Validation|General Knowledge",
  "Tension Wedge|Chabi|Carpet Weaving|Wedges driven to tighten warp|Wood|Masterweaver|Tensioning|Requires Field Validation|General Knowledge",
  "Weft Shuttle|Khoki-Qaleen|Carpet Weaving|Passes foundation weft|Wood|Kalimba|Weaving|Requires Field Validation|General Knowledge",
  "Point Maker|Qalam-Naksha|Carpet Weaving|Pen used to draw graph|Ink / Wood|Naqash|Drafting|Requires Field Validation|General Knowledge",

  // Papier Mâché Tools
  "Mould|Qalib / Mould|Papier Mâché|Form used during sakhtsazi shaping|Wood / Brass|Sakhtasazi Artisan|Shaping|Verified|PureKashmir",
  "Paint Brush|Qalam / Paint Brush|Papier Mâché|Used during naqashi decoration|Cat Hair|Naqqash|Painting|Verified|PureKashmir",
  "Burnisher|Mohra|Papier Mâché / Metal|Smoothing or finishing surface|Agate / Steel|Naqqash|Smoothing|Technical Reference|PureKashmir",
  "Pulp Bowl|Bana|Papier Mâché|Holds wet paper pulp|Clay|Sakhtasazi|Pulping|Requires Field Validation|General Knowledge",
  "Fine Detail Brush|Rez-Qalam|Papier Mâché|Microscopic line work|Cat Hair|Naqqash|Rez-e-Kari|Verified|Trade Usage",
  "Sanding Stone|Kurkut|Papier Mâché|Sands the rough Sakhta|Stone|Sakhtasazi|Sanding|Requires Field Validation|General Knowledge",
  "Lacquer Brush|Rogan-Qalam|Papier Mâché|Applies protective varnish|Soft Bristle|Naqqash|Varnishing|Requires Field Validation|General Knowledge",
  "Foil Applicator|Sone-Qalam|Papier Mâché|Applies real gold leaf|Wax Tip|Zarcod|Illumination|Requires Field Validation|General Knowledge",
  "Drying Rack|Takhtee|Papier Mâché|Holds wet objects|Wood|Naqqash|Drying|Requires Field Validation|General Knowledge",
  "Pattern Sketch|Naksha|Papier Mâché|Design drawing or pattern guide|Paper|Naqqash|Layout|Verified|PureKashmir",
  "Pestle|Muhul|Papier Mâché|Pounds waste paper|Wood|Sakhtasazi|Pounding|Verified|Trade Usage",
  "Stone Mortar|Kanz|Papier Mâché|Basin where pulp is crushed|Stone|Sakhtasazi|Pounding|Verified|Trade Usage",
  "Sieve|Channi|Papier Mâché|Filters lumps|Wire|Sakhtasazi|Refining|Requires Field Validation|General Knowledge",
  "Glue Pot|Saresh-Daan|Papier Mâché|Heats glue (Atij)|Copper|Sakhtasazi|Adhesive|Requires Field Validation|General Knowledge",
  "Cutting Knife|Chhura|Papier Mâché|Cuts Sakhta off mold|Steel|Sakhtasazi|Demolding|Requires Field Validation|General Knowledge",
  "Palette|Rung-Daan|Papier Mâché|Holds colors|Ceramic|Naqqash|Color Mixing|Requires Field Validation|General Knowledge",
  "Base Brush|Safeda-Qalam|Papier Mâché|Applies gesso primer|Bristle|Naqqash|Priming|Requires Field Validation|General Knowledge",
  "Water Cup|Aab-Daan|Papier Mâché|Rinses brushes|Copper|Naqqash|Cleaning|Requires Field Validation|General Knowledge",
  "Smoothing Rag|Kapae|Papier Mâché|Wipes excess lacquer|Cotton|Naqqash|Finishing|Requires Field Validation|General Knowledge",
  "Hand Lathe|Charkh|Papier Mâché|Trims circular boxes|Wood|Sakhtasazi|Trimming|Requires Field Validation|General Knowledge",

  // Copperware & Silverware Tools
  "Copper Hammer|Draz|Copperware|Hammer for shaping metal|Iron|Khar|Shaping|Verified|Greater Kashmir",
  "Copper Stake|Mekh|Copperware|Stake used for shaping metal|Iron|Khar|Shaping|Verified|Greater Kashmir",
  "Copper Anvil|Yandrewah|Copperware|Anvil for solid base|Iron|Khar|Forming|Verified|Greater Kashmir",
  "Engraving Chisel|Chisel|Copperware / Wood Carving|Engraving, cutting, carving|Steel|Naqash|Kandkari|Verified|Greater Kashmir",
  "Metal Punch|Punches|Copperware|Decorative impression and metal work|Steel|Naqash|Repousse|Verified|Greater Kashmir",
  "Metal File|Files|Copperware|Smoothing and shaping|Steel|Khar|Shaping|Verified|Greater Kashmir",
  "Copper Compass|Compass|Copperware / Wood Carving|Layout, circles, symmetry|Brass|Naqash|Geometry|Verified|Greater Kashmir",
  "Holding Stake|Basta|Copperware|Holding or shaping copperware|Metal / Wood|Khar|Shaping|Verified|Greater Kashmir",
  "Metal Tool|Thaj|Copperware|Specialized copperware tool|Metal|Khar|Metalwork|Requires Field Validation|Greater Kashmir",
  "Metal Tool|Sharanz|Copperware|Specialized copperware tool|Metal|Khar|Metalwork|Requires Field Validation|Greater Kashmir",
  "Metal Tool|Gosheper|Copperware|Specialized copperware tool|Metal|Khar|Metalwork|Requires Field Validation|Greater Kashmir",
  "Metal Tool|Angus|Copperware|Specialized copperware tool|Metal|Naqash|Metalwork|Requires Field Validation|Greater Kashmir",
  "Tongs|Sanaasi|Copperware|Holds hot metal|Iron|Khar|Handling|Requires Field Validation|General Knowledge",
  "Furnace|Bhatti|Copperware|Heats copper|Mud / Brick|Khar|Annealing|Requires Field Validation|General Knowledge",
  "Polishing Wheel|Charkh|Copperware|Buffs metal|Leather|Roshangar|Polishing|Requires Field Validation|General Knowledge",
  "Tin-Lining Tool|Kalai-Kalam|Copperware|Spreads molten tin|Cotton / Wood|Kalai-gar|Kalai|Verified|Trade Usage",
  "Wire Drawplate|Jantar|Silverware|Pulls silver into wire|Steel|Tar-Kash|Filigree|Verified|Trade Usage",
  "Soldering Iron|Kaviya|Silverware|Melts silver solder|Copper|Sonar|Soldering|Requires Field Validation|General Knowledge",
  "Bellows|Khalu|Copperware|Pumps air|Leather|Khar|Heating|Requires Field Validation|General Knowledge",
  "Pitch Bowl|Ral-Daan|Copperware|Holds vessel steady with resin|Iron|Naqash|Stabilization|Requires Field Validation|General Knowledge",

  // Walnut Wood Carving Tools
  "Carving Chisel|Chisels|Walnut Wood Carving|Engraving, cutting, carving|Steel|Wood Carver|Relief Carving|Verified|Incredible India",
  "Carving Gouge|Gouge|Walnut Wood Carving|Curved carving cuts|Steel|Wood Carver|Deep Carving|Verified|Incredible India",
  "Wooden Mallet|Mallet|Walnut Wood Carving|Striking chisels|Hardwood|Wood Carver|Percussion|Verified|Incredible India",
  "Wood Saw|Saw|Walnut Wood Carving|Cutting wood blocks|Steel|Khar|Rough Cutting|Verified|Incredible India",
  "Measuring Scale|Gaz / Scale|Walnut Wood Carving|Precise measurement|Brass|Wood Carver|Layout|Verified|Incredible India",
  "Carving Knife|Chhura|Walnut Wood Carving|Fine whittling|Steel|Wood Carver|Detailing|Requires Field Validation|General Knowledge",
  "Scraper|Randha|Walnut Wood Carving|Smooths flat surfaces|Steel|Wood Carver|Surface Prep|Requires Field Validation|General Knowledge",
  "Sanding Block|Kurkut|Walnut Wood Carving|Smooths wood|Stone / Paper|Wood Carver|Finishing|Requires Field Validation|General Knowledge",
  "Geometry Compass|Prakar / Compass|Walnut Wood Carving|Marks circles for Khatamband|Brass|Wood Carver|Layout|Requires Field Validation|General Knowledge",
  "Pattern Template|Ricna|Walnut Wood Carving|Scores precise angles|Metal|Khatamband Kaarigar|Marking|Historical / Archival|Archival",
  "Polishing Cloth|Kapae|Walnut Wood Carving|Applies walnut oil|Cotton|Wood Carver|Polishing|Requires Field Validation|General Knowledge",
  "Wood File|Reti|Walnut Wood Carving|Grinds rough edges|Steel|Wood Carver|Shaping|Requires Field Validation|General Knowledge",
  "V-Parting Tool|Tchok-Chhni|Walnut Wood Carving|Cuts sharp V-grooves|Steel|Wood Carver|Veining|Requires Field Validation|General Knowledge",
  "Calipers|Paimaish|Walnut Wood Carving|Measures thickness|Steel|Wood Carver|Measurement|Requires Field Validation|General Knowledge",
  "Sharpening Stone|Saan|Walnut Wood Carving|Sharpens chisels|Whetstone|Wood Carver|Maintenance|Requires Field Validation|General Knowledge",
  "Workbench|Mez|Walnut Wood Carving|Table for clamping|Timber|Wood Carver|Support|Requires Field Validation|General Knowledge",
  "Dust Brush|Moee|Walnut Wood Carving|Clears sawdust|Bristle|Wood Carver|Cleaning|Requires Field Validation|General Knowledge",
  "Wood Clamp|Shikunja|Walnut Wood Carving|Holds wood block|Iron|Wood Carver|Clamping|Requires Field Validation|General Knowledge",
  "Drawknife|Chhura-Bada|Walnut Wood Carving|Rapid stock removal|Steel|Khar|Shaping|Requires Field Validation|General Knowledge",
  "Finishing Scraper|Khurach|Walnut Wood Carving|Final surface smoothing|Steel|Wood Carver|Finishing|Requires Field Validation|General Knowledge"
];

export const toolsData = parseTools(rawTools);
