import { GlossaryEntry, GlossaryType, FieldValidationStatus } from './data';

const parseMotifs = (dataArray: string[]): GlossaryEntry[] => {
  return dataArray.map(line => {
    const parts = line.split('|');
    return {
      term: parts[0],
      localSpellingVariants: parts[1] || undefined,
      type: 'Motif' as GlossaryType,
      craftCategory: parts[2],
      definition: parts[3], // Visual description
      traditionalUsage: '',
      technicalMeaning: '',
      relatedTerms: [],
      exampleUsage: '',
      symbolicMeaning: parts[4],
      commonPlacement: parts[5],
      relatedTechnique: parts[6],
      historicalInfluence: parts[7],
      validationStatus: (parts[8] || 'Requires Field Validation') as FieldValidationStatus,
      sourceType: parts[9] || 'Online Evidence',
    };
  });
};

const rawMotifs = [
  // 1-20: Buta / Boteh / Paisley / Badam variations
  "Paisley Motif|Buta|Kani Shawls|A teardrop-shaped motif with a curved upper end.|Fertility and eternal life.|Corner borders and all-over field|Kani Weaving|Persian / Mughal|Verified|KashmKari",
  "Almond Motif|Badam / Badam Tarah|Papier Mâché|An almond-shaped variation of the paisley.|Life and fertility.|Box lids and vase bellies|Naqashi|Persian|Verified|KashmKari",
  "Elongated Paisley|Boteh|Sozni Embroidery|A highly stylized, elongated teardrop.|The cypress tree bent by the wind.|Shawl pallav (ends)|Satin Stitch|Safavid Persia|Verified|KashmKari",
  "Floral Paisley|Gul-Buta|Tilla Embroidery|A paisley shape filled entirely with micro-florals.|Abundance and nature's bounty.|Pheran borders|Couched Embroidery|Mughal|Verified|Trade Usage",
  "Double Paisley|Do-Buta|Carpet Weaving|Two boteh motifs facing each other.|Harmony and balance.|Carpet field|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Geometric Paisley|Khat-Buta|Walnut Wood Carving|A boteh rendered in sharp, geometric lines.|Structure and infinity.|Screen borders|Relief Carving|Central Asian|Requires Field Validation|General Knowledge",
  "Golden Paisley|Tilla-Buta|Silverware|A teardrop motif engraved with fine lines.|Prosperity.|Samovar bellies|Kandkari|Kashmiri|Requires Field Validation|General Knowledge",
  "Crown Paisley|Taj-Buta|Kani Shawls|A boteh topped with a crown-like floral spray.|Royalty and divine favor.|Royal Shawl Pallav|Kani Weaving|Mughal|Historical / Archival|Archival",
  "Intersecting Paisley|Joda-Badam|Sozni Embroidery|Overlapping almond motifs.|Union and connection.|Scarf corners|Sozni|Kashmiri|Requires Field Validation|General Knowledge",
  "Giant Paisley|Shah-Buta|Carpet Weaving|An oversized central boteh.|Dominance and singular focus.|Medallion center|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Vine Paisley|Zanjir-Buta|Crewel Embroidery|Paisleys connected by a continuous vine.|The eternal cycle of life.|Curtain borders|Chain Stitch|Persian|Verified|Trade Usage",
  "Bird Paisley|Murg-Buta|Papier Mâché|A boteh containing a hidden bird form.|Freedom within boundaries.|Decorative plates|Naqashi|Persian|Requires Field Validation|General Knowledge",
  "Miniature Paisley|Rez-Badam|Papier Mâché|Tiny, repeating almond shapes.|Abundance.|Pen box interiors|Rez-e-Kari|Kashmiri|Verified|Trade Usage",
  "Abstract Paisley|Tajrid-Buta|Gabba|A deconstructed paisley shape.|Modern expression of ancient forms.|Rug fields|Applique|Contemporary|Requires Field Validation|General Knowledge",
  "Shadow Paisley|Saya-Buta|Aari Embroidery|A boteh formed entirely of negative space.|The unseen divine.|Cushion covers|Aari|Kashmiri|Requires Field Validation|General Knowledge",
  "Corner Paisley|Kunj-Buta|Carpet Weaving|Quarter-paisleys nestled in the corners.|Protection from four directions.|Carpet spandrels|Knotting|Persian|Verified|Trade Usage",
  "Horned Paisley|Shakh-Buta|Copperware|A boteh with a sharp, elongated tip.|Protection and strength.|Tray edges|Repousse|Central Asian|Requires Field Validation|General Knowledge",
  "Nested Paisley|Badam-andar-Badam|Sozni Embroidery|Paisley within a paisley.|Infinite depth.|Shawl borders|Sozni|Kashmiri|Requires Field Validation|General Knowledge",
  "Dancing Paisley|Raqs-Buta|Kani Shawls|Asymmetrical boteh that appears to sway.|The wind in the garden.|Shawl fields|Kani Weaving|Mughal|Requires Field Validation|General Knowledge",
  "Textured Paisley|Dara-Buta|Namda|A boteh with raised, textured filling.|Earthly connection.|Felt rug center|Felting|Kashmiri|Requires Field Validation|General Knowledge",

  // 21-40: Chinar & Leaf Motifs
  "Chinar Leaf|Chinar / Boi|Walnut Wood Carving|The iconic five-pointed leaf of the Oriental Plane tree.|Kashmir's majestic natural beauty.|Furniture panels|Deep Carving|Indigenous Kashmiri|Verified|KashmKari",
  "Autumn Chinar|Zard-Chinar|Papier Mâché|Chinar leaf painted in fiery red and gold.|The cycle of seasons.|Vase exteriors|Naqashi|Indigenous Kashmiri|Verified|Trade Usage",
  "Chinar Branch|Shakh-e-Chinar|Crewel Embroidery|A branch bearing multiple chinar leaves.|Growth and family lineage.|Wall hangings|Chain Stitch|Kashmiri|Verified|Trade Usage",
  "Geometric Chinar|Khat-Chinar|Carpets|A rectilinear adaptation of the chinar leaf.|Structure of nature.|Border repeats|Knotting|Kashmiri|Requires Field Validation|General Knowledge",
  "Golden Chinar|Sone-Chinar|Tilla Embroidery|A chinar leaf embroidered in gold thread.|Royal heritage.|Pheran backs|Couched Tilla|Mughal|Verified|Trade Usage",
  "Micro Chinar|Rez-Chinar|Sozni Embroidery|Tiny chinar leaves forming a larger pattern.|The microcosm of nature.|Shawl fields|Sozni|Kashmiri|Requires Field Validation|General Knowledge",
  "Overlapping Chinar|Joda-Chinar|Copperware|Chinar leaves engraved in a dense overlapping pattern.|Abundance of the forest.|Tray centers|Kandkari|Kashmiri|Verified|Greater Kashmir",
  "Chinar Medallion|Gul-e-Chinar|Carpets|A central medallion formed by radiating chinar leaves.|The heart of Kashmir.|Carpet center|Knotting|Kashmiri|Verified|Trade Usage",
  "Abstract Chinar|Tajrid-Chinar|Namda|Simplified five-point star mimicking the leaf.|Nature's essence.|Felt borders|Aari|Kashmiri|Requires Field Validation|General Knowledge",
  "Chinar and Vine|Chinar-Zanjir|Wood Carving|Chinar leaves connected by looping vines.|The interconnectedness of life.|Screen borders|Relief Carving|Kashmiri|Verified|Incredible India",
  "Maple Leaf Variation|Kari-Patta|Crewel|A simplified leaf motif resembling maple or local ivy.|Growth and resilience.|Curtain fields|Chain Stitch|Kashmiri|Requires Field Validation|General Knowledge",
  "Serrated Leaf|Tez-Patta|Copperware|A leaf with sharply pointed edges.|Protection.|Vessel rims|Repousse|Persian|Requires Field Validation|General Knowledge",
  "Willow Leaf|Vir-Patta|Papier Mâché|Long, slender, drooping leaves.|Grace and flexibility.|Box edges|Naqashi|Kashmiri|Requires Field Validation|General Knowledge",
  "Lotus Leaf|Pamposh-Patta|Silverware|Broad, circular water leaves.|Purity and water.|Bowl bases|Engraving|Buddhist / Hindu|Historical / Archival|Archival",
  "Fern Motif|Kunj-Patta|Sozni Embroidery|Delicate, feathery leaf fronds.|The deep forest.|Shawl corners|Sozni|Kashmiri|Requires Field Validation|General Knowledge",
  "Vine Leaf|Dach-Patta|Wood Carving|Grapevine leaves.|Harvest and celebration.|Dining table borders|Deep Carving|Persian|Requires Field Validation|General Knowledge",
  "Apple Leaf|Tchoont-Patta|Crewel|Small, rounded leaves.|Orchards of Kashmir.|Cushion borders|Chain Stitch|Kashmiri|Requires Field Validation|General Knowledge",
  "Fallen Leaf|Khushk-Patta|Papier Mâché|Curled, asymmetrical leaf forms.|The passing of time.|Decorative panels|Naqashi|Contemporary|Requires Field Validation|General Knowledge",
  "Twin Leaves|Do-Patta|Tilla Embroidery|Two leaves sharing a single stem.|Partnership.|Pheran necklines|Tilla|Kashmiri|Requires Field Validation|General Knowledge",
  "Woven Leaf|Waft-Patta|Kani Shawls|A leaf form created purely through color blocking.|Structure.|Border accents|Kani Weaving|Kashmiri|Requires Field Validation|General Knowledge",

  // 41-60: Gul (Flower) & Floral Arrangements
  "Flower Motif|Gul|Papier Mâché|A generic, stylized floral blossom.|Beauty and the gardens of Paradise.|All-over patterns|Naqashi|Persian|Verified|KashmKari",
  "Rose Motif|Gulab|Shawls|A detailed, multi-petaled rose.|Love and divine beauty.|Pallav and fields|Sozni / Kani|Persian / Mughal|Verified|KashmKari",
  "Flower within Flower|Gul-andar-Gul|Papier Mâché|A complex motif where large petals contain smaller flowers.|Infinite beauty of creation.|Large vases and boxes|Naqashi|Mughal|Verified|KashmKari",
  "Thousand Flowers|Hazara|Papier Mâché|A dense, intricate pattern of countless tiny flowers.|The overwhelming beauty of nature.|Premium boxes|Rez-e-Kari|Persian|Verified|KashmKari",
  "Lotus Motif|Pamposh / Lotus|Wood Carving|A stylized water lily.|Purity, enlightenment, and rebirth.|Central panels|Deep Carving|Hindu / Buddhist|Verified|KashmKari",
  "Jasmine Motif|Yambarzal|Sozni Embroidery|Small, star-shaped white flowers.|Spring and new beginnings.|Shawl fields|Sozni|Kashmiri|Requires Field Validation|General Knowledge",
  "Iris Motif|Sosan|Papier Mâché|A tall flower with drooping petals.|Royalty and faith.|Vertical panels|Naqashi|Mughal|Requires Field Validation|General Knowledge",
  "Saffron Flower|Kong-Gul|Tilla Embroidery|The crocus flower showing distinct stigmas.|Wealth and Kashmiri identity.|Pheran borders|Couched Tilla|Indigenous Kashmiri|Verified|Trade Usage",
  "Tulip Motif|Gul-e-Lala|Carpet Weaving|A cup-shaped flower.|Perfect love and paradise.|Carpet borders|Knotting|Persian|Verified|Trade Usage",
  "Sunflower Motif|Gul-e-Aftab|Copperware|A large, radiating circular flower.|The sun and energy.|Tray centers|Kandkari|Persian|Requires Field Validation|General Knowledge",
  "Floral Sprig|Buti|Kani Shawls|A small, detached floral spray.|Modesty and elegance.|All-over shawl fields|Kani Weaving|Mughal|Verified|Trade Usage",
  "Floral Border|Hashiya|Carpet Weaving|A continuous band of repeating flowers.|Containment of paradise.|Carpet edges|Knotting|Persian|Verified|Trade Usage",
  "Blossoming Branch|Shakh-e-Gul|Crewel Embroidery|A branch heavy with blooms.|Fertility and spring.|Curtain fields|Chain Stitch|Kashmiri|Verified|Trade Usage",
  "Pomegranate Flower|Gul-e-Anar|Carpets|A bell-shaped blossom.|Immortality and fertility.|Field motifs|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Narcissus Motif|Nargis|Papier Mâché|A flower with a distinct central cup.|The eye of the beloved.|Vase details|Naqashi|Persian|Requires Field Validation|General Knowledge",
  "Marigold Motif|Genda|Namda|A densely packed, round flower.|Festivity and sun.|Rug corners|Aari|Indian|Requires Field Validation|General Knowledge",
  "Carnation Motif|Gul-e-Karanfal|Carpets|A flower with serrated edges.|Fascination and love.|Border guards|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Daffodil Motif|Zard-Gul|Sozni Embroidery|A trumpet-shaped spring flower.|Renewal.|Shawl fields|Sozni|Kashmiri|Requires Field Validation|General Knowledge",
  "Four-Petal Flower|Char-Gul|Wood Carving|A simple, geometric four-petal blossom.|The four directions.|Screen lattices|Relief Carving|Islamic|Verified|Incredible India",
  "Abstract Flower|Tajrid-Gul|Gabba|A deconstructed floral shape.|Modernity.|Rug centers|Applique|Contemporary|Requires Field Validation|General Knowledge",

  // 61-80: Arabesque, Vines, & Geometry
  "Arabesque|Arabesque / Islami|Copperware|Interlaced vine, tendril, floral or geometric pattern.|The infinite, indivisible nature of God.|Samovar surfaces|Kandkari|Islamic / Persian|Verified|KashmKari",
  "Vines and Creepers|Zanjir / Vines|Sozni Embroidery|Flowing botanical border or filler motif.|The eternal cycle of life and connection.|Borders|Sozni|Persian|Verified|KashmKari",
  "Lattice / Net|Jali|Wood Carving|A repeating geometric grid.|The veil between the physical and spiritual.|Window screens|Khatamband|Islamic Architectural|Technical Reference|KashmKari",
  "Geometric Medallion|Markaz|Carpet Weaving|A central, radiating geometric polygon.|The center of the universe.|Carpet center|Knotting|Central Asian|Technical Reference|Trade Usage",
  "Meander Border|Pech-Dar-Pech|Carpets|A continuous, winding geometric line.|The flow of water and eternity.|Outer carpet borders|Knotting|Greek / Central Asian|Requires Field Validation|General Knowledge",
  "Star Motif|Sitara|Wood Carving|An eight-point or six-point geometric star.|Divine guidance and light.|Khatamband panels|Relief Carving|Islamic|Verified|Incredible India",
  "Hexagon Grid|Shash-Pahlu|Papier Mâché|Repeating six-sided polygons.|Harmony and structure.|Box bottoms|Geometry|Islamic|Requires Field Validation|General Knowledge",
  "Chevron Pattern|Lahariya|Textiles|V-shaped repeating zig-zags.|Water and flowing rivers.|Woven borders|Twill Weave|Central Asian|Requires Field Validation|General Knowledge",
  "Interlocking Knots|Gira|Silverware|Complex geometric knots with no end.|Eternity and unbreakable bonds.|Bowl rims|Engraving|Islamic|Historical / Archival|Archival",
  "Diamond Motif|Heera|Carpets|A rhombus or diamond shape, often stepped.|Protection from the evil eye.|Tribal carpet fields|Knotting|Tribal/Nomadic|Requires Field Validation|General Knowledge",
  "Stepped Polygon|Gul|Carpets|An octagonal or polygonal medallion.|Tribal identity.|Carpet fields|Knotting|Turkmen|Historical / Archival|Archival",
  "Cross Motif|Salib|Namda|A geometric cross.|The four cardinal points.|Rug borders|Felting|Central Asian|Requires Field Validation|General Knowledge",
  "Scrolling Vine|Pech-o-Kham|Copperware|A vine that curls in on itself repeatedly.|Infinity.|Tray borders|Kandkari|Persian|Verified|Greater Kashmir",
  "Trellis Pattern|Jaal|Crewel Embroidery|An all-over diamond grid filled with florals.|The garden fence.|Curtain fields|Chain Stitch|Mughal|Verified|Trade Usage",
  "Cloud Band|Abr|Carpets|A stylized, undulating ribbon-like cloud.|The heavens and divine intervention.|Carpet fields|Knotting|Chinese / Persian|Requires Field Validation|General Knowledge",
  "Wave Motif|Mauj|Papier Mâché|A repeating scallop or wave pattern.|The lakes of Kashmir.|Vase bases|Naqashi|Kashmiri|Requires Field Validation|General Knowledge",
  "Checkerboard|Shatranji|Carpets|Alternating squares of color.|The dualities of life.|Borders|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Spiral Motif|Charkh|Wood Carving|A continuous spiral curve.|Cosmic energy.|Pillar bases|Deep Carving|Ancient|Requires Field Validation|General Knowledge",
  "Triangle Border|Kunj|Namda|A row of repeating triangles.|Mountains of Kashmir.|Rug edges|Aari|Kashmiri|Requires Field Validation|General Knowledge",
  "Key Pattern|Kilid|Silverware|A squared, labyrinthine border.|Security and hidden knowledge.|Box edges|Engraving|Greek / Persian|Requires Field Validation|General Knowledge",

  // 81-100: Fauna, Narrative, & Calligraphy
  "Birds|Murg / Birds|Papier Mâché|Nature-inspired decorative motif of songbirds.|Freedom and the soul's flight to the divine.|Decorative boxes and vases|Naqashi|Persian / Kashmiri|Verified|KashmKari",
  "Calligraphy|Khattati / Calligraphy|Copperware|Script-based sacred or decorative motif.|The divine word and truth.|Wall plates and bowls|Kandkari|Islamic|Verified|KashmKari",
  "Hunting Scene|Shikargah|Carpets|A narrative decorative composition showing hunters and prey.|The struggle of life and royal prowess.|Carpet fields|Knotting|Safavid Persia|Requires Field Validation|General Knowledge",
  "Peacock Motif|Moor|Papier Mâché|A regal bird with a sprawling tail.|Beauty, royalty, and immortality.|Large display items|Naqashi|Indian / Persian|Verified|Trade Usage",
  "Bulbul / Nightingale|Bulbul|Sozni Embroidery|A small songbird perched on a branch.|The lover singing to the rose (beloved).|Shawl borders|Sozni|Persian|Verified|Trade Usage",
  "Parrot Motif|Tota|Crewel Embroidery|A brightly colored parrot.|Joy and mimicry of the divine.|Wall hangings|Chain Stitch|Indian|Requires Field Validation|General Knowledge",
  "Deer Motif|Hiran|Carpets|A leaping deer or gazelle.|Grace and the pursuit of the divine.|Hunting carpets|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Lion Motif|Sher|Papier Mâché|A stylized lion, often attacking prey.|Power and majesty.|Box lids|Naqashi|Persian|Historical / Archival|Archival",
  "Fish Motif|Maach|Silverware|Stylized swimming fish.|Fertility, life, and the Dal Lake.|Bowl interiors|Engraving|Kashmiri|Historical / Archival|Archival",
  "Elephant Motif|Haathi|Wood Carving|A carved elephant form.|Strength and wisdom.|Table legs and bases|Relief Carving|Indian|Requires Field Validation|General Knowledge",
  "Dragon Motif|Azhdaha|Carpets|A mythical serpentine dragon.|Power and protection.|Specialty carpets|Knotting|Chinese / Persian|Historical / Archival|Archival",
  "Kufic Script|Khatt-e-Kufi|Wood Carving|Angular, geometric Arabic script.|Ancient divine revelation.|Mosque panels|Relief Carving|Islamic|Verified|Incredible India",
  "Nastaliq Script|Khatt-e-Nastaliq|Papier Mâché|Flowing, cursive Persian script.|Poetry and elegance.|Pen boxes|Naqashi|Persian|Verified|Trade Usage",
  "Bismillah Motif|Bismillah|Copperware|The invocation 'In the name of God' stylized as a shape.|Blessing and commencement.|Wall plates|Kandkari|Islamic|Verified|Trade Usage",
  "Poetic Couplet|Sher|Sozni Embroidery|A line of poetry woven or embroidered into the fabric.|Intellectual and spiritual expression.|Shawl borders|Sozni|Mughal / Persian|Historical / Archival|Archival",
  "Hoopoe Bird|Hudhud|Papier Mâché|The crested bird of Solomon.|Spiritual guidance and truth.|Decorative panels|Naqashi|Persian|Requires Field Validation|General Knowledge",
  "Horse Motif|Ghur|Carpets|A galloping steed.|Nobility and journey.|Shikargah carpets|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Falcon Motif|Baz|Wood Carving|A bird of prey.|Vision and royalty.|Decorative screens|Relief Carving|Persian|Requires Field Validation|General Knowledge",
  "Butterfly Motif|Pamposh-Murg|Crewel|A stylized butterfly.|Transformation and fleeting beauty.|Cushion covers|Chain Stitch|Kashmiri|Requires Field Validation|General Knowledge",
  "Duck Motif|Batak|Papier Mâché|Waterfowl floating on water.|The lakes of Kashmir.|Vase bases|Naqashi|Kashmiri|Requires Field Validation|General Knowledge",

  // 101-120: Architectural, Structural & Abstract Concepts
  "Tree of Life|Shajar-e-Hayat|Carpets|A symbolic tree composition growing from a base.|The connection between heaven, earth, and the underworld.|Carpet fields|Knotting|Ancient Near East|Technical Reference|KashmKari",
  "Garden Layout|Bagh|Carpets|A Persian garden-inspired arrangement with four quadrants (Chahar Bagh).|Paradise on earth.|Carpet fields|Knotting|Persian|Technical Reference|KashmKari",
  "Medallion|Markaz / Gumbad|Carpets|Central carpet layout motif.|The dome of a mosque or the center of the cosmos.|Carpet center|Knotting|Persian|Technical Reference|KashmKari",
  "Mihrab Motif|Mihrab|Carpets|An arched niche design.|The prayer niche pointing to Mecca.|Prayer rug fields|Knotting|Islamic Architectural|Verified|Trade Usage",
  "Arch Motif|Mehrab|Wood Carving|A pointed or scalloped arch.|Sacred space and transition.|Furniture backs|Deep Carving|Islamic Architectural|Verified|Incredible India",
  "Pillar Motif|Sutoon|Silverware|A carved or engraved column.|Support and strength.|Samovar bases|Engraving|Architectural|Requires Field Validation|General Knowledge",
  "Dome Motif|Gumbad|Papier Mâché|A hemispherical shape.|The vault of heaven.|Box lids|Naqashi|Islamic Architectural|Requires Field Validation|General Knowledge",
  "Minaret Motif|Minar|Wood Carving|A tall, slender tower form.|The call to the divine.|Screen edges|Relief Carving|Islamic Architectural|Requires Field Validation|General Knowledge",
  "Fountain Motif|Fawara|Carpets|Water flowing from a central point.|The springs of Paradise.|Bagh carpet centers|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Gateway Motif|Darwaza|Wood Carving|An elaborate doorway frame.|Transition and welcome.|Wall panels|Deep Carving|Architectural|Requires Field Validation|General Knowledge",
  "Window Motif|Daricha|Papier Mâché|A small framed view.|Perspective and inner life.|Decorative plates|Naqashi|Architectural|Requires Field Validation|General Knowledge",
  "Brickwork Pattern|Khisht|Carpets|Repeating rectangular blocks.|Building and foundation.|Borders|Knotting|Architectural|Requires Field Validation|General Knowledge",
  "Tile Pattern|Kashi|Papier Mâché|Geometric star and cross interlocking tiles.|Cosmic order.|Box surfaces|Geometry|Persian|Requires Field Validation|General Knowledge",
  "Step Motif|Zeena|Namda|Ascending stair-step geometry.|Spiritual elevation.|Rug borders|Applique|Architectural|Requires Field Validation|General Knowledge",
  "Water Channel|Nahr|Carpets|Straight lines connecting to a central pool.|The rivers of Paradise.|Bagh carpets|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Pool Motif|Hauz|Carpets|A central square or diamond representing water.|Purity and reflection.|Bagh carpet centers|Knotting|Persian|Requires Field Validation|General Knowledge",
  "Mountain Motif|Koh|Namda|Triangular peaks.|The Himalayas surrounding Kashmir.|Rug edges|Felting|Kashmiri|Requires Field Validation|General Knowledge",
  "Sunburst Motif|Shamsa|Papier Mâché|A radiating sun disk.|Divine light and royal power.|Manuscript covers|Naqashi|Persian / Mughal|Historical / Archival|Archival",
  "Moon Motif|Mahtab|Silverware|A crescent moon.|The passage of time and Islamic identity.|Bowl interiors|Engraving|Islamic|Requires Field Validation|General Knowledge",
  "Star and Crescent|Sitara-o-Hilal|Wood Carving|The moon and star combined.|Faith and the cosmos.|Decorative panels|Relief Carving|Islamic|Verified|Incredible India"
];

export const motifsData = parseMotifs(rawMotifs);
