import { GlossaryEntry } from './data';

export const workshopData: GlossaryEntry[] = [
  {
    term: "Karkhan",
    localSpellingVariants: "Karkhana",
    type: "Workshop Term",
    craftCategory: "All Crafts",
    definition: "Workshop or production space.",
    workshopMeaning: "The physical space where artisans gather, collaborate, and execute their craft under the guidance of a master.",
    whoUsesIt: "Karkhandars, Ustads, Shagirds",
    whereItIsUsed: "Across all traditional craft sectors in Kashmir.",
    traditionalUsage: "The center of craft production and knowledge transfer.",
    technicalMeaning: "A specialized, often naturally lit manufacturing space.",
    relatedTerms: ["Karkhandar", "Ustad"],
    exampleUsage: "The Karkhan was filled with the rhythmic sound of looms.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews / Field Documentation"
  },
  {
    term: "Naqash",
    localSpellingVariants: "Nakaash",
    type: "Workshop Term",
    craftCategory: "Papier Mâché / Woodwork",
    definition: "Designer or pattern-maker.",
    workshopMeaning: "The master illustrator who draws or paints the intricate motifs onto the raw material.",
    whoUsesIt: "Master painters, Wood carvers",
    whereItIsUsed: "Papier Mâché painting studios, Walnut carving workshops.",
    traditionalUsage: "Responsible for executing traditional floral and geometric patterns.",
    technicalMeaning: "Surface ornamenter.",
    relatedTerms: ["Naqashi", "Naksha"],
    exampleUsage: "The Naqash carefully painted the Chinar leaf.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews"
  },
  {
    term: "Talim",
    localSpellingVariants: "Taleem",
    type: "Workshop Term",
    craftCategory: "Kani Shawls / Carpets",
    definition: "Coded weaving instruction.",
    workshopMeaning: "A written script translating a design into a sequence of knots and colors, chanted aloud during weaving.",
    whoUsesIt: "Masterweavers, Talim-Writers",
    whereItIsUsed: "Carpet and Kani shawl looms.",
    traditionalUsage: "Eliminates the need for graphical point-paper designs.",
    technicalMeaning: "Algorithmic pattern notation.",
    relatedTerms: ["Naksha", "Kani"],
    exampleUsage: "The weaver followed the Talim flawlessly.",
    validationStatus: "Field Verified",
    sourceType: "Field Documentation"
  },
  {
    term: "Naksha",
    localSpellingVariants: "Nakhsha",
    type: "Workshop Term",
    craftCategory: "Carpets",
    definition: "Design drawing or grid pattern.",
    workshopMeaning: "The original visual blueprint or painted graph from which the Talim is written.",
    whoUsesIt: "Naqash, Talim-Writer",
    whereItIsUsed: "Design studios prior to weaving.",
    traditionalUsage: "The primary visual reference before coding.",
    technicalMeaning: "Point-paper design matrix.",
    relatedTerms: ["Talim", "Naqash"],
    exampleUsage: "The Naksha for the new carpet took a month to paint.",
    validationStatus: "Field Verified",
    sourceType: "Field Documentation"
  },
  {
    term: "Kani",
    localSpellingVariants: "Kanis",
    type: "Workshop Term",
    craftCategory: "Kani Shawls",
    definition: "Small wooden bobbin/spool.",
    workshopMeaning: "Eyeless wooden sticks around which colored weft threads are wound for tapestry weaving.",
    whoUsesIt: "Kani weavers",
    whereItIsUsed: "Horizontal Kani looms.",
    traditionalUsage: "Replaces the shuttle in complex pattern weaving.",
    technicalMeaning: "Discontinuous weft bobbin.",
    relatedTerms: ["Tujli", "Talim"],
    exampleUsage: "The weaver used over fifty kanis for a single row.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews"
  },
  {
    term: "Tujli",
    localSpellingVariants: "Tujis, Toji",
    type: "Workshop Term",
    craftCategory: "Kani Shawls",
    definition: "Bobbins/sticks used in Kani shawl weaving.",
    workshopMeaning: "Another specific term used by artisans to refer to the wooden sticks holding the colored yarn.",
    whoUsesIt: "Kani weavers",
    whereItIsUsed: "Kanihama weaving centers.",
    traditionalUsage: "Manipulated rapidly to interlock colors.",
    technicalMeaning: "Weft carrier sticks.",
    relatedTerms: ["Kani", "Weft / Bana"],
    exampleUsage: "He organized his Tujlis by color before starting.",
    validationStatus: "Requires Field Validation",
    sourceType: "Online Evidence / Archival"
  },
  {
    term: "Wasta",
    localSpellingVariants: "Vasta",
    type: "Workshop Term",
    craftCategory: "All Crafts",
    definition: "Master artisan or senior instructor.",
    workshopMeaning: "A highly skilled foreman or chief artisan who directs the work of apprentices.",
    whoUsesIt: "Shagirds, Karkhandars",
    whereItIsUsed: "Across various craft workshops, notably woodwork and masonry.",
    traditionalUsage: "The primary transmitter of craft knowledge.",
    technicalMeaning: "Master craftsman / Overseer.",
    relatedTerms: ["Ustad", "Karkhan"],
    exampleUsage: "The Wasta corrected the apprentice's technique.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews"
  },
  {
    term: "Kalimba",
    localSpellingVariants: "Kal-baf",
    type: "Workshop Term",
    craftCategory: "Carpets",
    definition: "Carpet weaver.",
    workshopMeaning: "Specific terminology relating to the artisan who ties knots on a vertical carpet loom.",
    whoUsesIt: "Carpet industry",
    whereItIsUsed: "Carpet weaving Karkhans.",
    traditionalUsage: "The primary producer of knotted pile rugs.",
    technicalMeaning: "Loom operator.",
    relatedTerms: ["Qaleen"],
    exampleUsage: "The Kalimba worked silently, following the chanted Talim.",
    validationStatus: "Requires Field Validation",
    sourceType: "Online Evidence"
  },
  {
    term: "Rangrez",
    localSpellingVariants: "Ranger",
    type: "Workshop Term",
    craftCategory: "Textiles",
    definition: "Dyer or color specialist.",
    workshopMeaning: "The master of color chemistry who dyes yarn using natural or synthetic pigments.",
    whoUsesIt: "Weavers, Karkhandars",
    whereItIsUsed: "Dyeing vats and specialized color workshops.",
    traditionalUsage: "Crucial for determining the final palette of a shawl or carpet.",
    technicalMeaning: "Textile colorist.",
    relatedTerms: ["Rang", "Yarn"],
    exampleUsage: "The Rangrez achieved a brilliant crimson using madder root.",
    validationStatus: "Field Verified",
    sourceType: "Field Documentation"
  },
  {
    term: "Sozni",
    localSpellingVariants: "Sozan",
    type: "Workshop Term",
    craftCategory: "Embroidery",
    definition: "Fine needle embroidery.",
    workshopMeaning: "The practice and product of exceptionally delicate needlework, typically on Pashmina.",
    whoUsesIt: "Sozni-kash (Needleworkers)",
    whereItIsUsed: "Home-based setups and specialized embroidery Karkhans.",
    traditionalUsage: "Used to embellish luxury shawls with microscopic floral patterns.",
    technicalMeaning: "Satin and stem stitch surface ornamentation.",
    relatedTerms: ["Sozan-kaari", "Pashmina"],
    exampleUsage: "The Sozni work on the shawl took two years.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews"
  },
  {
    term: "Sozan-kaari",
    localSpellingVariants: "Sozankari",
    type: "Workshop Term",
    craftCategory: "Embroidery",
    definition: "Needlework practice.",
    workshopMeaning: "The overarching craft and professional practice of needle embroidery.",
    whoUsesIt: "Embroidery guilds",
    whereItIsUsed: "Throughout the Kashmir valley.",
    traditionalUsage: "Denotes the profession of fine stitching.",
    technicalMeaning: "The act of embroidering.",
    relatedTerms: ["Sozni"],
    exampleUsage: "His family had been involved in Sozan-kaari for generations.",
    validationStatus: "Verified",
    sourceType: "Archival"
  },
  {
    term: "Aari",
    localSpellingVariants: "Ari",
    type: "Workshop Term",
    craftCategory: "Embroidery",
    definition: "Hooked needle embroidery.",
    workshopMeaning: "The tool and the resulting chain-stitch embroidery style used on thicker fabrics like Dusooti.",
    whoUsesIt: "Ari-kash, Crewel workers",
    whereItIsUsed: "Rug and upholstery manufacturing.",
    traditionalUsage: "Allows for rapid filling of large design areas.",
    technicalMeaning: "Hooked awl chain-stitching.",
    relatedTerms: ["Adda", "Crewel"],
    exampleUsage: "The Aari work gave the rug a beautiful texture.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews"
  },
  {
    term: "Adda",
    localSpellingVariants: "Ada",
    type: "Workshop Term",
    craftCategory: "Embroidery",
    definition: "Wooden embroidery frame.",
    workshopMeaning: "The large wooden frame on which fabric is stretched taut for Aari, Crewel, or Tilla embroidery.",
    whoUsesIt: "Embroiderers",
    whereItIsUsed: "Embroidery Karkhans.",
    traditionalUsage: "Maintains fabric tension for precise stitching.",
    technicalMeaning: "Tensioning frame.",
    relatedTerms: ["Aari", "Zardozi"],
    exampleUsage: "The fabric was stretched tightly across the Adda.",
    validationStatus: "Field Verified",
    sourceType: "Field Documentation"
  },
  {
    term: "Zardozi",
    localSpellingVariants: "Zardouzi",
    type: "Workshop Term",
    craftCategory: "Embroidery",
    definition: "Metallic thread embroidery.",
    workshopMeaning: "Heavy, elaborate embroidery using metallic threads, beads, and sequins.",
    whoUsesIt: "Specialized embroiderers",
    whereItIsUsed: "Bridal and formal wear workshops.",
    traditionalUsage: "Ornamentation of heavy fabrics like velvet.",
    technicalMeaning: "Raised metallic couching.",
    relatedTerms: ["Tilla", "Adda"],
    exampleUsage: "The Zardozi borders were incredibly heavy and ornate.",
    validationStatus: "Verified",
    sourceType: "Trade Usage"
  },
  {
    term: "Tilla",
    localSpellingVariants: "Tillya",
    type: "Workshop Term",
    craftCategory: "Embroidery",
    definition: "Gold or silver thread embroidery.",
    workshopMeaning: "The specific Kashmiri style of couching imitation gold or silver threads onto pherans and shawls.",
    whoUsesIt: "Tilla-doz",
    whereItIsUsed: "Garment ornamentation.",
    traditionalUsage: "Essential for Kashmiri bridal trousseaus.",
    technicalMeaning: "Metallic thread couching.",
    relatedTerms: ["Zardozi", "Pheran"],
    exampleUsage: "The silver Tilla contrasted beautifully with the black velvet.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews"
  },
  {
    term: "Kar-e-Qalamdani",
    localSpellingVariants: "Kar-i-Kalamdani",
    type: "Workshop Term",
    craftCategory: "Papier Mâché",
    definition: "Decorated paper-pulp craft.",
    workshopMeaning: "The classical historical name for Papier Mâché, literally translating to 'pen-case work'.",
    whoUsesIt: "Historians, Senior Artisans",
    whereItIsUsed: "Academic and historical craft discussions.",
    traditionalUsage: "Refers to the original objects (pen cases) that popularized the craft.",
    technicalMeaning: "Painted paper-mâché craft.",
    relatedTerms: ["Papier Mache", "Naqashi"],
    exampleUsage: "Kashmir's Papier Mâché was originally known as Kar-e-Qalamdani.",
    validationStatus: "Archival Term",
    sourceType: "Archival"
  },
  {
    term: "Naqashi",
    localSpellingVariants: "Nakkashi",
    type: "Workshop Term",
    craftCategory: "Papier Mâché",
    definition: "Painted surface decoration.",
    workshopMeaning: "The process of painting intricate floral and geometric patterns onto the molded paper base.",
    whoUsesIt: "Naqash",
    whereItIsUsed: "Papier Mâché studios.",
    traditionalUsage: "The defining aesthetic stage of the craft.",
    technicalMeaning: "Surface illumination / miniature painting.",
    relatedTerms: ["Naqash", "Kar-e-Qalamdani"],
    exampleUsage: "The Naqashi on the vase took three weeks to complete.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews"
  },
  {
    term: "Pashm",
    localSpellingVariants: "Pasham",
    type: "Workshop Term",
    craftCategory: "Pashmina",
    definition: "Fine under-fleece used for pashmina.",
    workshopMeaning: "The raw, unspun cashmere fiber harvested from the Changthangi goat.",
    whoUsesIt: "Nomads, Spinners, Traders",
    whereItIsUsed: "From Ladakh high altitudes to Srinagar spinning wheels.",
    traditionalUsage: "The raw material for the world's finest shawls.",
    technicalMeaning: "Capra hircus laniger undercoat.",
    relatedTerms: ["Pashmina"],
    exampleUsage: "The raw Pashm was sorted by color and quality.",
    validationStatus: "Field Verified",
    sourceType: "Field Documentation"
  },
  {
    term: "Pashmina",
    localSpellingVariants: "Pashmineh",
    type: "Workshop Term",
    craftCategory: "Pashmina",
    definition: "Fine textile made from pashm.",
    workshopMeaning: "The finished woven fabric, celebrated globally for its softness and warmth.",
    whoUsesIt: "Weavers, Wearers",
    whereItIsUsed: "Luxury textile markets globally.",
    traditionalUsage: "Woven into shawls, stoles, and scarves.",
    technicalMeaning: "Cashmere woven textile.",
    relatedTerms: ["Pashm", "Warp / Tana"],
    exampleUsage: "She draped the pure Pashmina shawl over her shoulders.",
    validationStatus: "Verified",
    sourceType: "Trade Usage"
  },
  {
    term: "Warp / Tana",
    localSpellingVariants: "Taana",
    type: "Workshop Term",
    craftCategory: "Textiles",
    definition: "Lengthwise yarns on loom.",
    workshopMeaning: "The foundational threads held in high tension on the loom, through which the weft is woven.",
    whoUsesIt: "Weavers, Warp dressers",
    whereItIsUsed: "All looms (Carpet, Kani, Plain weave).",
    traditionalUsage: "Provides the structural backbone of the textile.",
    technicalMeaning: "Longitudinal loom yarns.",
    relatedTerms: ["Weft / Bana", "Adda"],
    exampleUsage: "The silk Tana was stretched tightly across the loom.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews"
  },
  {
    term: "Weft / Bana",
    localSpellingVariants: "Baana",
    type: "Workshop Term",
    craftCategory: "Textiles",
    definition: "Crosswise yarns woven through warp.",
    workshopMeaning: "The filling yarn carried by a shuttle or kani that creates the fabric and pattern.",
    whoUsesIt: "Weavers",
    whereItIsUsed: "All weaving processes.",
    traditionalUsage: "Interlaces with the Tana to form cloth.",
    technicalMeaning: "Transverse filling yarn.",
    relatedTerms: ["Warp / Tana", "Kani"],
    exampleUsage: "The weaver inserted a red Bana to form the flower motif.",
    validationStatus: "Field Verified",
    sourceType: "Artisan Interviews"
  }
];
