import { GlossaryEntry, GlossaryType, FieldValidationStatus } from './data';

const parseProducts = (dataArray: string[]): GlossaryEntry[] => {
  return dataArray.map(line => {
    const parts = line.split('|');
    return {
      term: parts[0],
      localSpellingVariants: parts[1] || undefined,
      type: 'Product' as GlossaryType,
      craftCategory: parts[2],
      definition: parts[3], // Use / Function
      traditionalUsage: '',
      technicalMeaning: '',
      relatedTerms: [],
      exampleUsage: '',
      productType: parts[4],
      primaryMaterials: parts[5],
      coreTechniques: parts[6],
      commonSizes: parts[7],
      commonMotifs: parts[8],
      qualityIndicators: parts[9],
      authenticityRisks: parts[10],
      validationStatus: (parts[11] || 'Requires Field Validation') as FieldValidationStatus,
      sourceType: parts[12] || 'Online Evidence',
    };
  });
};

const rawProducts = [
  // 1-40: Pashmina, Shawls & Textiles
  "Pashmina Shawl|Pashmina|Pashmina & Shawls|A luxury wrap made entirely of hand-spun and hand-woven Pashmina.|Wrap / Accessory|Pure Pashm|Spinning, Weaving|200x100 cm|Solid or Hashiya|Softness, warmth, fine micron count|Machine-spun yarn, Merino/Silk blends|Verified|Ministry of Textiles",
  "Plain Pashmina Shawl|Sada Pashmina|Pashmina & Shawls|An un-embroidered Pashmina shawl showcasing the pure weave.|Wrap|Pure Pashm|Spinning, Weaving|200x100 cm|None (Solid)|Flawless weave, softness|Machine-made|Verified|Trade Usage",
  "Sozni Pashmina Shawl|Sozni Pashmina|Pashmina & Shawls|A Pashmina shawl extensively embroidered with Sozni needlework.|Luxury Wrap|Pashm, Silk Thread|Sozni Embroidery|200x100 cm|Boteh, Hazara|Stitch density, flat back|Machine embroidery|Verified|Ministry of Textiles",
  "Tilla Pashmina Shawl|Tilla Pashmina|Pashmina & Shawls|A Pashmina shawl adorned with metallic Tilla embroidery.|Occasion Wrap|Pashm, Metallic Zari|Couched Tilla|200x100 cm|Chinar, Floral Sprig|Neatness of couching|Faux plastic zari|Verified|Trade Usage",
  "Kani Shawl|Kani|Pashmina & Shawls|A tapesty-woven shawl made with wooden bobbins, often covered in motifs.|Heirloom Wrap|Pashm|Kani Weaving|200x100 cm|Taj-Buta, Florals|Woven density, color depth|Machine-woven jacquard|Verified|Ministry of Textiles",
  "Jamawar Shawl|Jamawar|Pashmina & Shawls|An all-over heavily patterned shawl (Kani or Sozni) leaving no base fabric visible.|Bridal/Heirloom Wrap|Pashm|Kani or Sozni|200x100 cm, 220x110 cm|All-over Boteh|Density of pattern, weight|Machine-made imitations|Verified|Trade Usage",
  "Do-Shala|Do-Shala|Pashmina & Shawls|Two identical shawls stitched back-to-back, traditionally worn by men.|Men's Garment|Pashm|Weaving, Stitching|220x110 cm (Double)|Solid with borders|Seamless stitching|Synthetic wool|Historical / Archival|Archival",
  "Stole|Stole|Pashmina & Shawls|A narrower version of a shawl, typically worn over the shoulders.|Accessory|Pashm, Silk, Wool|Weaving, Embroidery|200x70 cm|Florals, Stripes|Softness, drape|Machine-made blends|Technical Reference|Trade Usage",
  "Scarf|Scarf|Pashmina & Shawls|A small woven textile piece worn around the neck.|Accessory|Pashm, Silk|Weaving|160x30 cm|Geometric, Florals|Finish, softness|Viscose blends|Technical Reference|Trade Usage",
  "Muffler|Gul-band|Pashmina & Shawls|A narrow, thick winter scarf for men.|Winter Accessory|Wool, Pashm|Twill Weaving|150x25 cm|Checks, Stripes|Warmth, durability|Machine-woven acrylic|Verified|Trade Usage",
  "Wrap|Chadar|Pashmina & Shawls|A generic term for a large piece of fabric wrapped around the body.|Garment|Wool, Pashm|Weaving|Varies|Plain|Warmth|Blends|Technical Reference|Trade Usage",
  "Rumal|Square Shawl|Pashmina & Shawls|A square-shaped shawl, historically popular in the European market.|Accessory|Pashm|Weaving, Sozni|100x100 cm, 140x140 cm|Central Medallion|Symmetry, finesse|Machine-made|Verified|Trade Usage",
  "Pheran|Pheran|Pashmina & Shawls|The traditional long, loose cloak worn in Kashmir during winter.|Garment|Patto, Tweed, Velvet|Tailoring, Tilla|Custom (Ankle to Knee length)|Tilla necklines|Warmth, lining quality|Synthetic fabrics|Verified|Trade Usage",
  "Tilla Pheran|Tilla Pheran|Pashmina & Shawls|A premium Pheran featuring heavy metallic Tilla embroidery on the collar and cuffs.|Bridal/Occasion Garment|Velvet, Pashm, Zari|Couched Tilla|Custom|Chinar, Florals|Heavy, neat Tilla work|Machine Tilla|Verified|Trade Usage",
  "Aari Shawl|Aari Shawl|Pashmina & Shawls|A woolen shawl heavily embroidered with continuous Aari chain stitch.|Winter Wrap|Merino, Sheep Wool|Aari Embroidery|200x100 cm|Large Florals, Vines|Neatness of chain stitch|Machine Aari|Verified|Trade Usage",
  "Reversible Shawl|Do-Rukha Shawl|Pashmina & Shawls|A shawl that has the exact same (or inverted color) pattern on both sides.|Luxury Wrap|Pashm|Reversible Sozni / Weaving|200x100 cm|Boteh|Flawless back|Machine-made|Verified|Trade Usage",
  "Ring Pashmina|Ring Shawl|Pashmina & Shawls|A shawl woven so finely it can pass through a finger ring.|Luxury Wrap|Pure Pashm|Ultra-fine spinning/weaving|200x100 cm|Plain|Can pass through a ring|Water-soluble nylon warps|Verified|Trade Usage",
  "Palldar Shawl|Pallav-dar|Pashmina & Shawls|A shawl featuring heavy embroidery or weaving exclusively on the two short ends (pallavs).|Wrap|Pashm|Weaving, Sozni|200x100 cm|Boteh on ends|Symmetry|Machine-made|Verified|Trade Usage",
  "Hashidar Shawl|Hashia-dar|Pashmina & Shawls|A shawl featuring a narrow embroidered or woven border running along all four edges.|Wrap|Pashm|Weaving, Sozni|200x100 cm|Vines, Small Florals|Straight borders|Machine-made|Verified|Trade Usage",
  "Chand-Dar Shawl|Chand-Dar|Pashmina & Shawls|A shawl featuring a central moon (medallion) and four quarter-moons in the corners.|Wrap|Pashm|Weaving, Sozni|200x100 cm|Medallion|Perfect centering|Machine-made|Verified|Trade Usage",
  "Jaali Shawl|Jali-dar|Pashmina & Shawls|A shawl covered in an all-over net or trellis pattern.|Wrap|Pashm|Sozni, Weaving|200x100 cm|Trellis, Floral grid|Consistency of grid|Machine-made|Verified|Trade Usage",
  "Aksi Shawl|Aks-Dar|Pashmina & Shawls|A reversible shawl where the pattern on the back is a different color than the front.|Luxury Wrap|Pashm|Complex Sozni|200x100 cm|Florals|Clean color separation|Impossible to machine-make|Verified|Trade Usage",
  "Semi-Pashmina Shawl|Raffal-Pashmina|Pashmina & Shawls|A commercial blend of Merino wool and Pashmina.|Wrap|Merino, Pashm|Weaving|200x100 cm|Plain or Sozni|Softness|Sold as pure Pashmina|Requires Field Validation|Trade Usage",
  "Silk-Pashmina Stole|Silk-Blend|Pashmina & Shawls|A stole with a silk warp and pashmina weft for added sheen.|Accessory|Silk, Pashm|Weaving|200x70 cm|Plain|Lustrous finish|Sold as 100% Pashmina|Verified|Trade Usage",
  "Kani-Sozni Shawl|Kani-Sozni|Pashmina & Shawls|A shawl embroidered to look exactly like a Kani weave.|Wrap|Pashm, Silk Thread|Counted-thread Sozni|200x100 cm|Blocky Boteh|Mimicry accuracy|Sold as real Kani|Verified|Trade Usage",
  "Paper-Mache Shawl|Papier-Mache Shawl|Pashmina & Shawls|A shawl featuring thick, multi-colored Sozni stitching resembling Naqashi painting.|Wrap|Pashm|Thick Sozni|200x100 cm|Hazara, Florals|Vibrant colors, thick texture|Machine-made|Verified|Trade Usage",
  "Kalamkari Pashmina|Kalamkari|Pashmina & Shawls|A shawl where motifs are hand-painted and then outlined with Sozni.|Art Wrap|Pashm, Dyes|Painting, Sozni|200x100 cm|Mythological, Florals|Paint fastness|Screen printed|Verified|Trade Usage",
  "Shibori Pashmina|Tie-Dye Pashmina|Pashmina & Shawls|A modern Pashmina shawl dyed using tie-dye techniques.|Contemporary Wrap|Pashm|Tie-Dye|200x100 cm|Abstract|Color fastness|Machine printed|Technical Reference|Trade Usage",
  "Ombre Pashmina|Shaded Pashmina|Pashmina & Shawls|A shawl dyed in a gradient from light to dark.|Modern Wrap|Pashm|Dip Dyeing|200x100 cm|Gradient|Smooth transition|Machine printed|Technical Reference|Trade Usage",
  "Checkered Pashmina|Charkhana Pashmina|Pashmina & Shawls|A pashmina woven with a geometric check pattern.|Wrap|Pashm|Weaving|200x100 cm|Checks|Symmetry|Machine-made|Verified|Trade Usage",
  "Striped Pashmina|Khat-Dar Pashmina|Pashmina & Shawls|A pashmina woven with longitudinal stripes.|Wrap|Pashm|Weaving|200x100 cm|Stripes|Symmetry|Machine-made|Verified|Trade Usage",
  "Zari Pashmina|Tilla-Dar|Pashmina & Shawls|A pashmina woven with metallic threads running through the warp/weft.|Luxury Wrap|Pashm, Zari|Weaving|200x100 cm|Metallic sheen|Quality of Zari|Plastic Zari|Requires Field Validation|Trade Usage",
  "Vintage Jamawar|Antique Shawl|Pashmina & Shawls|A Kani or Sozni shawl dating back 50-200 years.|Collectible|Pashm|Kani, Sozni|Varies|Boteh|Age, provenance, patina|Fake aging|Verified|Trade Usage",
  "Summer Pashmina|Sheer Pashmina|Pashmina & Shawls|An extremely loose-woven pashmina for summer wear.|Accessory|Pashm|Loose Weaving|200x70 cm|Plain|Lightness|Viscose blends|Technical Reference|Trade Usage",
  "Bridal Pashmina|Shaadi Shawl|Pashmina & Shawls|A heavily embroidered (Sozni or Tilla) red or white shawl for brides.|Bridal Garment|Pashm|Sozni, Tilla|200x100 cm|Florals, Gold|Heavy workmanship|Machine-made|Verified|Trade Usage",
  "Baby Blanket|Pashmina Baby Blanket|Pashmina & Shawls|A small, ultra-soft pashmina weave for infants.|Utility|Pashm|Weaving|100x100 cm|Plain|Softness|Synthetic blends|Technical Reference|Trade Usage",
  "Pashmina Suit Piece|Suit Length|Pashmina & Shawls|Unstitched lengths of pashmina/wool fabric for making Salwar Kameez.|Garment Material|Pashm, Wool|Weaving, Sozni|3-5 meters|Borders|Fabric drape|Blends|Verified|Trade Usage",
  "Crewel Curtain|Crewel Parda|Pashmina & Shawls (Embroidery)|Thick cotton/canvas fabric heavily embroidered with wool for home decor.|Home Decor|Dusooti, Wool|Crewel Chain Stitch|Varies|Tree of Life, Large Florals|Density of stitch|Machine Crewel|Verified|Trade Usage",
  "Crewel Cushion Cover|Cushion Cover|Pashmina & Shawls (Embroidery)|A small canvas square embroidered with crewel work.|Home Decor|Dusooti, Wool|Crewel Chain Stitch|16x16, 18x18 inches|Florals|Density|Machine Crewel|Technical Reference|Trade Usage",
  "Aari Bedspread|Bedcover|Pashmina & Shawls (Embroidery)|A large fabric piece covered in Aari chain stitch for beds.|Home Decor|Cotton, Wool/Silk|Aari|Double Bed Size|Chinar, Vines|Neatness|Machine Aari|Technical Reference|Trade Usage",

  // 41-70: Carpets & Floor Coverings
  "Kashmiri Hand-Knotted Carpet|Kal Baffi Qaleen|Carpets & Floor Coverings|A premium floor covering created by hand-tying individual knots.|Carpet|Silk, Wool, Cotton|Persian Knotting|3x5, 4x6, 6x9, 9x12 ft|Medallion, Shikargah|Knot density (KPSI)|Machine-made, Hand-tufted|Verified|Ministry of Textiles",
  "Silk Carpet|Resham Qaleen|Carpets & Floor Coverings|A high-density carpet made entirely with a silk pile.|Luxury Carpet|Pure Silk|Persian Knotting|4x6, 6x9 ft|Gul-andar-Gul, Medallion|Knot density, sheen|Art-silk (Viscose)|Verified|Trade Usage",
  "Wool Carpet|Oon Qaleen|Carpets & Floor Coverings|A durable, rich-colored hand-knotted carpet with a wool pile.|Durable Carpet|Wool, Cotton Warp|Persian Knotting|5x8, 8x10 ft|Geometric, Floral|Pile thickness, knot clarity|Machine-made wool|Verified|Trade Usage",
  "Silk-on-Silk Carpet|Pure Silk Qaleen|Carpets & Floor Coverings|An ultra-luxury carpet where both the pile and the warp/weft are pure silk.|Investment Carpet|Pure Silk|Persian Knotting|3x5, 4x6 ft|Tree of Life|Extreme knot density (up to 1000 KPSI)|Art-silk|Verified|Trade Usage",
  "Wool-on-Cotton Carpet|Standard Qaleen|Carpets & Floor Coverings|The standard configuration for durable Kashmiri wool carpets.|Carpet|Wool Pile, Cotton Warp|Persian Knotting|6x9, 9x12 ft|Medallion|Durability|Machine-made|Technical Reference|Trade Usage",
  "Prayer Rug|Ja-Namaz|Carpets & Floor Coverings|A small hand-knotted carpet featuring a directional arch (Mihrab).|Functional Carpet|Silk, Wool|Persian Knotting|2.5x4 ft|Mihrab, Pillars|Knot density|Machine-woven|Verified|Trade Usage",
  "Runner|Runner|Carpets & Floor Coverings|A long, narrow carpet designed for hallways or stairs.|Carpet|Silk, Wool|Persian Knotting|2.5x8, 3x12 ft|Repeating Medallions|Straightness|Machine-woven|Technical Reference|Trade Usage",
  "Area Rug|Qaleen|Carpets & Floor Coverings|A generic trade term for room-sized carpets (e.g., 8x10 ft).|Carpet|Silk, Wool|Persian Knotting|8x10 ft+|Garden Layout|Knot density|Machine-woven|Technical Reference|Trade Usage",
  "Wall Hanging|Deewari Qaleen|Carpets & Floor Coverings|A finely knotted carpet meant specifically for display as art.|Art Carpet|Silk|Persian Knotting|2x3, 3x5 ft|Portraits, Calligraphy|Clarity of image|Machine tapestries|Technical Reference|Trade Usage",
  "Namda|Namda|Carpets & Floor Coverings|A non-woven felted wool rug decorated with colorful Aari embroidery.|Felt Rug|Wool|Felting, Aari Embroidery|3x5, 4x6 ft|Chinar, Florals|Felt density, stitch neatness|Machine-felted, synthetic|Verified|Ministry of Textiles",
  "Gabba|Gabba|Carpets & Floor Coverings|An upcycled rug made by appliquing pieces of old dyed blankets.|Applique Rug|Recycled Wool|Applique, Chain Stitch|4x6, 6x9 ft|Geometrics, Chinar|Neatness of applique|Machine-made|Verified|Trade Usage",
  "Chain Stitch Rug|Aari Rug|Carpets & Floor Coverings|A flat canvas rug completely covered in concentric chain stitch embroidery.|Embroidered Rug|Wool, Dusooti|Zalakdozi (Chain Stitch)|4x6, 6x9 ft|Florals, Tree of Life|Coverage density|Machine Aari|Verified|Trade Usage",
  "Staple Carpet|Art-Silk Carpet|Carpets & Floor Coverings|A carpet hand-knotted with synthetic viscose (staple) to mimic silk.|Commercial Carpet|Viscose, Cotton|Persian Knotting|4x6, 6x9 ft|Medallion|Price|Sold as pure silk|Verified|Trade Usage",
  "Tribal Rug|Gujjar Rug|Carpets & Floor Coverings|A coarsely knotted or flat-woven rug made by nomadic communities.|Tribal Carpet|Coarse Wool|Turkish Knotting|3x5 ft|Geometrics|Authenticity|Commercial copies|Requires Field Validation|General Knowledge",
  "Circular Carpet|Gol Qaleen|Carpets & Floor Coverings|A hand-knotted carpet in a perfect circular shape.|Carpet|Silk, Wool|Circular Knotting|4 ft, 6 ft diameter|Medallion|Perfect circle|Machine-made|Verified|Trade Usage",
  "Double-Sided Carpet|Do-Rukha Qaleen|Carpets & Floor Coverings|A marvel carpet displaying perfect knotting on both sides.|Masterpiece|Silk|Reversible Knotting|3x5 ft|Florals|Flawless reverse|Impossible to fake|Verified|Trade Usage",
  "Hunting Carpet|Shikargah Qaleen|Carpets & Floor Coverings|A carpet depicting elaborate hunting scenes with animals and riders.|Thematic Carpet|Silk, Wool|Persian Knotting|4x6, 6x9 ft|Shikargah|Detailing of figures|Machine-woven|Verified|Trade Usage",
  "Garden Carpet|Bagh Qaleen|Carpets & Floor Coverings|A carpet divided into quadrants representing the four gardens of Paradise.|Thematic Carpet|Silk, Wool|Persian Knotting|6x9 ft|Bagh, Water Channels|Symmetry|Machine-woven|Verified|Trade Usage",
  "Tree of Life Carpet|Shajar-e-Hayat|Carpets & Floor Coverings|A carpet featuring a massive central tree growing from the base.|Thematic Carpet|Silk, Wool|Persian Knotting|4x6 ft|Tree of Life, Birds|Knot density|Machine-woven|Verified|Trade Usage",
  "Kilim|Gelim|Carpets & Floor Coverings|A flat-woven, tapestry-style rug with no pile.|Flatweave Rug|Wool|Slit-tapestry|3x5, 4x6 ft|Stepped Polygons|Tightness of weave|Machine-woven|Requires Field Validation|Trade Usage",
  "Overdyed Carpet|Vintage Overdyed|Carpets & Floor Coverings|An old, faded carpet that is chemically bleached and re-dyed a vibrant solid color.|Modernized Rug|Wool|Dyeing|Varies|Faded Medallion|Color fastness|Machine-printed vintage|Verified|Trade Usage",
  "Patchwork Carpet|Patchwork Rug|Carpets & Floor Coverings|A modern rug made by sewing together fragments of old, damaged carpets.|Upcycled Rug|Old Carpets|Cutting, Stitching|Varies|Abstract|Strong seams|Machine-printed patchwork|Verified|Trade Usage",
  "Embossed Carpet|Carved Carpet|Carpets & Floor Coverings|A carpet where the pile is scissor-carved to different heights to create a 3D effect.|Textural Carpet|Silk, Wool|Knotting, Relief Shearing|3x5 ft|Florals|Smooth shearing|Machine-tufted|Requires Field Validation|Trade Usage",
  "Medallion Carpet|Gumbad Qaleen|Carpets & Floor Coverings|The classic carpet layout featuring a large central geometric or floral medallion.|Classic Carpet|Silk, Wool|Persian Knotting|6x9, 9x12 ft|Medallion, Spandrels|Symmetry|Machine-woven|Verified|Trade Usage",
  "All-Over Carpet|Jaal Qaleen|Carpets & Floor Coverings|A carpet pattern with no central medallion, covered entirely in repeating motifs.|Classic Carpet|Silk, Wool|Persian Knotting|6x9 ft|Arabesque, Trellis|Pattern continuity|Machine-woven|Verified|Trade Usage",
  "Silk Highlight Carpet|Highlight Qaleen|Carpets & Floor Coverings|A wool carpet where specific motifs are knotted in silk to make them pop.|Blended Carpet|Wool, Silk|Persian Knotting|6x9 ft|Florals|Sheen contrast|Viscose highlights|Verified|Trade Usage",
  "Wagoo Mat|Wagoo|Carpets & Floor Coverings|A traditional woven reed mat used as a base layer for flooring.|Reed Mat|Typha Reeds|Plaiting, Weaving|3x6 ft|Geometrics|Tightness of weave|Plastic mats|Historical / Archival|Archival",
  "Silk Runner|Resham Runner|Carpets & Floor Coverings|A pure silk narrow carpet for hallways.|Luxury Runner|Pure Silk|Persian Knotting|2.5x10 ft|Repeating Medallions|Straightness|Art-silk|Technical Reference|Trade Usage",
  "Namda Cushion Cover|Namda Cushion|Carpets & Floor Coverings|A small felted square embroidered with Aari work, used for home decor.|Decor Felt|Wool|Felting, Aari|16x16 inches|Chinar|Felt density|Machine felt|Requires Field Validation|Trade Usage",
  "Gabba Wall Hanging|Gabba Art|Carpets & Floor Coverings|A small, highly detailed Gabba applique piece meant for the wall.|Decor Applique|Recycled Wool|Applique|2x3 ft|Chinar, Geometrics|Stitching|Machine applique|Requires Field Validation|Trade Usage",

  // 71-110: Papier Mâché
  "Qalamdan / Kalamdan|Pen Box|Papier Mâché|A traditional elongated box historically used by scribes for pens and ink.|Historical Box|Paper Pulp, Paints, Gold|Sakhtsazi, Naqashi|10x3x2 inches|Hazara, Gul-andar-Gul|Painting micro-detail|Wood/Cardboard base|Verified|Ministry of Textiles",
  "Papier Mâché Box|Dabba|Papier Mâché|A generic term for round, square, or rectangular decorative boxes.|Decorative Box|Paper Pulp, Paints|Sakhtsazi, Naqashi|Varies|Chinar, Birds|Smoothness, paint quality|MDF/Wood base|Verified|Trade Usage",
  "Jewelry Box|Jewelry Box|Papier Mâché|A lined box with compartments for storing jewelry.|Utility Box|Paper Pulp, Velvet lining|Sakhtsazi, Naqashi|8x6x4 inches|Hazara, Gold Illumination|Hinge quality, painting|Wood base|Technical Reference|Trade Usage",
  "Trinket Box|Pill Box|Papier Mâché|A very small round or heart-shaped box for small items.|Souvenir Box|Paper Pulp, Paints|Sakhtsazi, Naqashi|2 to 3 inches|Florals|Detail at small scale|Wood base|Technical Reference|Trade Usage",
  "Tray|Tray|Papier Mâché|A flat tray used for serving or display, often heavily varnished for durability.|Serving/Display|Paper Pulp/Wood, Paints|Naqashi|12x18 inches|Chinar, Arabesque|Varnish quality|MDF base|Verified|Trade Usage",
  "Vase|Guldan|Papier Mâché|A decorative vessel for holding dry flowers.|Display Vessel|Paper Pulp, Paints|Sakhtsazi, Naqashi|8 to 24 inches tall|Birds, Florals|Symmetry of form|Plastic/Clay base|Verified|Trade Usage",
  "Bowl|Kasa|Papier Mâché|A decorative bowl, historically used for dry fruits or display.|Display Bowl|Paper Pulp, Paints|Sakhtsazi, Naqashi|6 to 12 inches diameter|Chinar, Arabesque|Smooth interior|Wood base|Verified|Trade Usage",
  "Cup|Pyala|Papier Mâché|A decorative cup, often sold in sets with coasters or trays.|Display|Paper Pulp, Paints|Sakhtsazi, Naqashi|3 to 4 inches|Florals|Finish|Not food safe|Technical Reference|Trade Usage",
  "Coaster Set|Coasters|Papier Mâché|A set of 4-6 flat discs used under glasses, stored in a matching box.|Utility/Display|Wood/Pulp, Paints|Naqashi|4 inches diameter|Chinar, Hazara|Heat/Water resistance of varnish|MDF|Verified|Trade Usage",
  "Wall Plate|Deewari Rakab|Papier Mâché|A flat or slightly curved plate designed specifically for wall hanging.|Wall Art|Paper Pulp, Paints|Sakhtsazi, Naqashi|8 to 16 inches|Calligraphy, Hunting|Perfectly flat surface|Wood/MDF|Verified|Trade Usage",
  "Ornament|Bauble / Bell|Papier Mâché|Small hanging decorations, highly popular for Christmas exports.|Export Souvenir|Paper Pulp, Paints|Sakhtsazi, Naqashi|2 to 4 inches|Florals, Stars|Lightness|Plastic cores|Verified|Trade Usage",
  "Decorative Egg|Egg|Papier Mâché|A solid or hollow egg shape, heavily decorated (resembling Faberge eggs).|Export Souvenir|Paper Pulp, Paints|Sakhtsazi, Naqashi|3 to 6 inches|Hazara, Gold|Symmetry|Wood cores|Verified|Trade Usage",
  "Lamp Base|Lamp Stand|Papier Mâché|A tall, weighted base for a table lamp, wired for electricity.|Home Decor|Paper Pulp/Wood, Paints|Sakhtsazi, Naqashi|12 to 24 inches|Arabesque|Stability, wiring|Wood base|Verified|Trade Usage",
  "Mask|Mask|Papier Mâché|A molded face mask, often depicting historical or mythological figures.|Wall Art|Paper Pulp, Paints|Sakhtsazi, Naqashi|Life-size|Traditional|Molding quality|Plastic bases|Requires Field Validation|Trade Usage",
  "Pen Stand|Pen Stand|Papier Mâché|A desk accessory for holding pens upright.|Desk Accessory|Paper Pulp, Paints|Sakhtsazi, Naqashi|4x4 inches|Chinar, Florals|Finish|Wood base|Technical Reference|Trade Usage",
  "Tissue Box|Tissue Cover|Papier Mâché|A decorative cover that slides over standard cardboard tissue boxes.|Home Decor|Wood/Pulp, Paints|Naqashi|Standard Tissue size|Hazara|Fit|MDF base|Technical Reference|Trade Usage",
  "Letter Holder|Letter Rack|Papier Mâché|A desk accessory with slots for mail.|Desk Accessory|Wood/Pulp, Paints|Naqashi|8x6 inches|Florals|Finish|Wood base|Technical Reference|Trade Usage",
  "Bangle Box|Bangle Box|Papier Mâché|A long cylindrical box designed to hold Indian bangles.|Utility Box|Paper Pulp, Paints|Sakhtsazi, Naqashi|10 inches long|Chinar|Hinge/Clasp|Wood base|Technical Reference|Trade Usage",
  "Elephant Figure|Haathi|Papier Mâché|A 3D sculptured elephant, highly popular in the Indian domestic market.|Sculpture|Paper Pulp, Paints|Sakhtsazi, Naqashi|4 to 12 inches|Florals|Proportions|Wood/Wire armature|Verified|Trade Usage",
  "Cat Figure|Cat|Papier Mâché|A 3D sculptured cat, often painted in the Hazara style.|Sculpture|Paper Pulp, Paints|Sakhtsazi, Naqashi|6 to 12 inches|Hazara|Proportions|Wood/Wire armature|Verified|Trade Usage",
  "Picture Frame|Frame|Papier Mâché|A decorated border for photographs or mirrors.|Home Decor|Wood/Pulp, Paints|Naqashi|5x7, 8x10 inches|Chinar, Vines|Straight edges|MDF base|Technical Reference|Trade Usage",
  "Chess Board|Shatranj|Papier Mâché|A functional chess board painted with Naqashi, often including painted pieces.|Game/Decor|Wood, Paints|Naqashi|14x14 inches|Checkers, Hunting scenes|Durability of varnish|MDF base|Verified|Trade Usage",
  "Book Stand|Rehal|Papier Mâché|An X-shaped folding stand for holding sacred books, decorated with Naqashi.|Religious/Decor|Wood, Paints|Naqashi|12 to 18 inches|Calligraphy, Arabesque|Hingeless folding|Wood base|Verified|Trade Usage",
  "Samovar Display|Papier Mache Samovar|Papier Mâché|A non-functional, purely decorative replica of the traditional copper samovar.|Sculpture/Display|Paper Pulp, Paints|Sakhtsazi, Naqashi|12 to 18 inches|Hazara, Chinar|Symmetry|Clay bases|Requires Field Validation|Trade Usage",
  "Shikara Boat Model|Shikara|Papier Mâché|A miniature replica of the iconic Dal Lake boat.|Souvenir|Wood/Pulp, Paints|Naqashi|6 to 12 inches|Florals|Detailing|Wood base|Verified|Trade Usage",
  "Camel Figure|Camel|Papier Mâché|A 3D sculptured camel, heavily painted.|Sculpture|Paper Pulp, Paints|Sakhtsazi, Naqashi|6 to 12 inches|Hazara|Proportions|Wire armature|Requires Field Validation|Trade Usage",
  "Duck Box|Duck Box|Papier Mâché|A box molded in the shape of a sitting duck, where the top half lifts off.|Novelty Box|Paper Pulp, Paints|Sakhtsazi, Naqashi|6 to 8 inches|Feathers, Florals|Fit of the lid|Wood base|Requires Field Validation|Trade Usage",
  "Apple Box|Apple Box|Papier Mâché|A box shaped and painted exactly like a Kashmiri apple.|Novelty Box|Paper Pulp, Paints|Sakhtsazi, Naqashi|Real apple size|Realistic Painting|Realism|Wood base|Verified|Trade Usage",
  "Chinar Leaf Tray|Chinar Tray|Papier Mâché|A tray physically molded into the shape of a Chinar leaf.|Display Tray|Paper Pulp, Paints|Sakhtsazi, Naqashi|10 to 14 inches|Autumn Chinar|Edge strength|MDF base|Verified|Trade Usage",
  "Bell|Ghanti|Papier Mâché|A hollow bell shape with a clapper, used as a Christmas ornament.|Export Souvenir|Paper Pulp, Paints|Sakhtsazi, Naqashi|3 to 5 inches|Stars, Florals|Sound (if applicable)|Plastic cores|Technical Reference|Trade Usage",
  "Star Ornament|Star|Papier Mâché|A 3D star shape for hanging.|Export Souvenir|Paper Pulp, Paints|Sakhtsazi, Naqashi|3 to 4 inches|Geometrics|Sharp points|Plastic cores|Technical Reference|Trade Usage",
  "Moon Ornament|Crescent|Papier Mâché|A crescent moon shaped hanging ornament.|Export Souvenir|Paper Pulp, Paints|Sakhtsazi, Naqashi|3 to 4 inches|Florals|Smooth curves|Plastic cores|Technical Reference|Trade Usage",
  "Heart Box|Heart Box|Papier Mâché|A heart-shaped trinket box.|Souvenir Box|Paper Pulp, Paints|Sakhtsazi, Naqashi|3 to 5 inches|Florals, Gold|Fit of lid|MDF base|Technical Reference|Trade Usage",
  "Table|Papier Mache Table|Papier Mâché|A small wooden side table entirely coated and painted in the Naqashi style.|Furniture|Wood, Paints, Lacquer|Naqashi|18 to 24 inches high|Hunting Scenes, Hazara|Varnish durability|MDF|Verified|Trade Usage",
  "Room Divider|Screen|Papier Mâché|A 3 or 4-panel folding screen painted with Naqashi.|Furniture|Wood, Paints|Naqashi|6 ft tall|Hazara, Chinar|Durability|MDF|Verified|Trade Usage",
  "Clock|Wall Clock|Papier Mâché|A decorative wall clock face painted in Naqashi.|Home Decor|Wood/Pulp, Clock Mechanism|Naqashi|10 to 14 inches|Numerals, Florals|Mechanism quality|MDF|Technical Reference|Trade Usage",
  "Mirror|Naqashi Mirror|Papier Mâché|A wall mirror with a wide, heavily painted frame.|Home Decor|Wood/Pulp, Glass|Naqashi|Varies|Chinar|Frame straightness|MDF|Technical Reference|Trade Usage",
  "Candle Holder|Candlestick|Papier Mâché|A decorative stand for candles (usually requires a metal insert for safety).|Home Decor|Paper Pulp/Wood|Sakhtsazi, Naqashi|6 to 12 inches|Florals|Fire safety|Wood base|Verified|Trade Usage",
  "Waste Bin|Dustbin|Papier Mâché|A decorative cylindrical or square bin for dry office waste.|Utility/Decor|Paper Pulp/Wood|Sakhtsazi, Naqashi|12 inches high|Chinar|Durability|MDF/Tin|Technical Reference|Trade Usage",
  "Dry Fruit Box|Dry Fruit Box|Papier Mâché|A large box with 4-6 internal compartments for serving nuts and dried fruits.|Utility/Display|Wood/Pulp, Paints|Naqashi|10 to 14 inches|Hazara, Arabesque|Finish of compartments|MDF base|Verified|Trade Usage",

  // 111-150: Walnut Wood Carving, Khatamband & Pinjrakari
  "Carved Walnut Table|Mez|Walnut Wood|A side or coffee table featuring deep relief carving on the top and legs.|Furniture|Walnut Wood|Relief/Deep Carving|18 to 36 inches|Chinar, Lotus, Dragon|Depth of carving, wood seasoning|Kikar/Mango wood stained dark|Verified|Ministry of Textiles",
  "Jewelry Box|Dabba|Walnut Wood|A small, lined box with a carved lid and secret locking mechanisms.|Utility Box|Walnut Wood|Relief Carving|8x6x4 inches|Chinar, Vine|Seamless joinery, lock function|Cheaper woods|Verified|Trade Usage",
  "Dry Fruit Box|Dry Fruit Bowl|Walnut Wood|A large carved bowl or compartmented box for serving Kashmiri dry fruits.|Servingware|Walnut Wood|Deep Carving|10 to 14 inches|Chinar, Grapes|Smooth finish|Cheaper woods|Verified|Trade Usage",
  "Wall Panel|Deewari Panel|Walnut Wood|A flat wooden slab carved with intricate scenes, hung as art.|Wall Art|Walnut Wood|Undercut/Relief Carving|Varies|Hunting, Village Scenes, Chinar|3D depth of undercut|CNC Machine carved|Verified|Trade Usage",
  "Room Divider|Screen / Partition|Walnut Wood|A 3 or 4-panel folding screen featuring heavy carving or Pinjrakari lattice.|Furniture|Walnut Wood|Carving, Pinjrakari|6 ft tall|Chinar, Lattice|Stability, hinge quality|MDF / CNC carved|Verified|Trade Usage",
  "Chair|Kursi|Walnut Wood|A dining or lounge chair with carved backrests and legs.|Furniture|Walnut Wood|Deep Carving, Joinery|Standard|Lotus, Dragon|Ergonomics, joinery strength|Cheaper woods|Verified|Trade Usage",
  "Cabinet|Almari|Walnut Wood|A large storage cabinet or sideboard, heavily carved on all doors and panels.|Furniture|Walnut Wood|Carving, Joinery|Varies|Chinar|Wood seasoning (preventing warp)|MDF|Verified|Trade Usage",
  "Bed Headboard|Bed|Walnut Wood|A massive carved headboard for luxury beds.|Furniture|Walnut Wood|Deep Carving|Queen/King width|Chinar, Lotus|Symmetry, depth|Cheaper woods|Verified|Trade Usage",
  "Mirror Frame|Aina-Daan|Walnut Wood|A carved frame for wall mirrors.|Home Decor|Walnut Wood|Relief Carving|Varies|Vines, Florals|Frame straightness|MDF|Technical Reference|Trade Usage",
  "Serving Tray|Tray|Walnut Wood|A flat tray with carved edges and handles; the center is usually smooth or lightly carved under glass.|Servingware|Walnut Wood|Relief Carving|12x18 inches|Chinar|Flatness, wood grain|Cheaper woods|Verified|Trade Usage",
  "Book Stand|Rehal|Walnut Wood|An X-shaped folding stand for sacred books, carved from a single block of wood (hingeless).|Religious/Decor|Walnut Wood|Hingeless Carving, Lattice|12 to 18 inches|Chinar, Geometrics|Smooth folding|Two pieces joined with metal hinges|Verified|Trade Usage",
  "Walking Stick|Chhari|Walnut Wood|A sturdy walking cane featuring a deeply carved handle (often a dragon or bird head).|Accessory|Walnut Wood|Carving, Turning|36 inches|Dragon, Eagle, Vine|Strength of shaft|Cheaper woods|Verified|Trade Usage",
  "Fruit Bowl|Bowl|Walnut Wood|A large, deep bowl carved from a single block of walnut wood.|Servingware|Walnut Wood|Turning, Relief Carving|10 to 14 inches diameter|Chinar|Smooth interior|Cheaper woods|Verified|Trade Usage",
  "Nesting Tables|Set of Tables|Walnut Wood|A set of 3 or 4 small tables of decreasing size that slide under one another.|Furniture|Walnut Wood|Carving, Joinery|12 to 24 inches high|Chinar|Fit, stability|MDF|Verified|Trade Usage",
  "Dining Table|Dining Set|Walnut Wood|A massive table, usually glass-topped to protect the deep carving underneath, with 6-8 carved chairs.|Furniture|Walnut Wood|Deep Carving, Joinery|6 to 8 ft long|Chinar, Grapevine|Wood seasoning|Cheaper woods|Verified|Trade Usage",
  "Lamp Stand|Lamp Base|Walnut Wood|A turned and carved wooden column wired for a lamp.|Home Decor|Walnut Wood|Turning, Carving|12 to 24 inches|Vines, Geometrics|Stability|Cheaper woods|Technical Reference|Trade Usage",
  "Clock Frame|Wall Clock|Walnut Wood|A carved wooden housing for a clock mechanism.|Home Decor|Walnut Wood|Relief Carving|10 to 14 inches|Chinar|Finish|MDF|Technical Reference|Trade Usage",
  "Tissue Box|Tissue Cover|Walnut Wood|A carved wooden cover for standard tissue boxes.|Home Decor|Walnut Wood|Relief Carving|Standard|Chinar|Fit|MDF|Technical Reference|Trade Usage",
  "Sofa Set|Sofa|Walnut Wood|A living room seating set (3+1+1) featuring carved wooden frames and upholstered seats.|Furniture|Walnut Wood, Fabric|Carving, Upholstery|Varies|Chinar, Lotus|Joinery strength|Cheaper woods|Verified|Trade Usage",
  "Elephant Figure|Haathi|Walnut Wood|A 3D sculptured elephant, often with an undercut baby elephant carved inside its belly.|Sculpture|Walnut Wood|Undercut Carving|4 to 12 inches|Lifelike|Skill of undercut|CNC|Verified|Trade Usage",
  "Chess Set|Shatranj|Walnut Wood|A carved chess board with hand-carved wooden pieces.|Game/Decor|Walnut Wood|Carving, Turning|14x14 inches|Traditional|Detailing of pieces|MDF|Verified|Trade Usage",
  "Cigar Box|Humidor|Walnut Wood|A tightly sealed box for cigars, taking advantage of walnut's density.|Utility Box|Walnut Wood|Joinery, Carving|10x8x4 inches|Plain or Chinar|Seal quality|Cheaper woods|Technical Reference|Trade Usage",
  "Letter Opener|Paper Knife|Walnut Wood|A decorative desk accessory carved in the shape of a blade.|Desk Accessory|Walnut Wood|Carving|8 inches|Chinar handle|Sharpness|Cheaper woods|Technical Reference|Trade Usage",
  "Coaster Set|Coasters|Walnut Wood|A set of 4-6 carved wooden discs in a matching holder.|Utility/Decor|Walnut Wood|Carving|4 inches diameter|Chinar|Flatness|MDF|Technical Reference|Trade Usage",
  "Key Holder|Key Rack|Walnut Wood|A carved wall plaque with hooks for keys.|Home Decor|Walnut Wood|Carving|8x6 inches|Chinar, Birds|Finish|MDF|Technical Reference|Trade Usage",
  "Bellows|Khalu|Walnut Wood|Decorative or functional fireplace bellows with carved wooden handles and leather.|Utility/Decor|Walnut Wood, Leather|Carving, Leatherwork|18 inches|Chinar|Airflow|Cheaper woods|Requires Field Validation|Trade Usage",
  "Peg Table|Peg Table|Walnut Wood|A small, tall, round side table.|Furniture|Walnut Wood|Turning, Carving|24 inches high|Chinar|Stability|Cheaper woods|Technical Reference|Trade Usage",
  "Magazine Rack|Magazine Holder|Walnut Wood|A floor-standing rack with carved side panels.|Home Decor|Walnut Wood|Carving, Joinery|18x12 inches|Chinar, Lattice|Stability|MDF|Technical Reference|Trade Usage",
  "Bedside Table|Nightstand|Walnut Wood|A small cabinet with drawers for the bedroom.|Furniture|Walnut Wood|Carving, Joinery|24 inches high|Chinar|Drawer glide|MDF|Technical Reference|Trade Usage",
  "Writing Desk|Secretary Desk|Walnut Wood|A desk with carved panels and multiple small drawers.|Furniture|Walnut Wood|Carving, Joinery|4 ft wide|Chinar, Lotus|Wood seasoning|Cheaper woods|Verified|Trade Usage",
  "Khatamband Ceiling Panel|Khatamband|Khatamband|An interlocking geometric wooden panel used for traditional Kashmiri ceilings.|Architecture|Fir/Deodar Wood|Geometric Joinery|Varies|Star, Hexagon|Seamless fit|Plywood/CNC|Verified|Ministry of Textiles",
  "Decorative Ceiling Module|Khatamband Module|Khatamband|A pre-assembled section of Khatamband sold for export or modern home installation.|Home Decor|Fir/Deodar Wood|Geometric Joinery|2x2 ft, 4x4 ft|Star, Hexagon|Joinery|CNC|Verified|Trade Usage",
  "Khatamband Box|Khatamband Box|Khatamband|A modern adaptation applying the interlocking ceiling technique to a decorative box.|Utility Box|Fir, Walnut|Joinery|8x6x4 inches|Geometrics|Joinery|CNC|Requires Field Validation|Trade Usage",
  "Pinjrakari Screen|Pinjra Panel|Pinjrakari|A delicate, see-through geometric wooden lattice used for windows or partitions.|Architecture|Deodar, Walnut|Lattice Joinery|Varies|Hexagons, Stars|Fragility/Strength|CNC MDF|Verified|General Knowledge",
  "Lattice Panel|Jali Panel|Pinjrakari|A smaller Pinjrakari panel used as a decorative wall hanging or cabinet door insert.|Home Decor|Deodar, Walnut|Lattice Joinery|Varies|Geometrics|Joinery|CNC MDF|Verified|Trade Usage",
  "Window Screen|Daricha Pinjra|Pinjrakari|The traditional Kashmiri window covering allowing light and ventilation while maintaining privacy.|Architecture|Deodar Wood|Lattice Joinery|Custom|Geometrics|Weather resistance|CNC|Historical / Archival|Archival",
  "Partition Panel|Room Divider|Pinjrakari|A folding screen made entirely of see-through Pinjrakari lattice.|Furniture|Deodar, Walnut|Lattice Joinery|6 ft tall|Geometrics|Stability|CNC MDF|Verified|Trade Usage",
  "Pinjrakari Lamp|Lattice Lamp|Pinjrakari|A modern lamp utilizing the lattice to cast geometric shadows.|Home Decor|Deodar Wood|Lattice Joinery|12 to 24 inches|Geometrics|Wiring|CNC|Requires Field Validation|Trade Usage",
  "Pinjrakari Tray|Lattice Tray|Pinjrakari|A serving tray featuring a Pinjrakari base protected by glass.|Servingware|Deodar, Walnut|Lattice Joinery|12x18 inches|Geometrics|Glass seal|CNC|Requires Field Validation|Trade Usage",
  "Geometric Wall Art|Khatamband Art|Khatamband|A single large Khatamband star/hexagon motif framed as modern wall art.|Wall Art|Fir, Walnut|Joinery|24x24 inches|Star|Wood contrast|CNC|Requires Field Validation|Trade Usage",

  // 151-180: Copperware, Silverware & Metal Crafts
  "Samovar|Samovar|Copperware|The iconic Kashmiri tea boiler with a central chimney for hot coals, heavily engraved.|Utility/Display Vessel|Copper, Tin|Forging, Kandkari (Engraving)|12 to 24 inches tall|Chinar, Arabesque|Quality of engraving, weight|Machine-pressed copper|Verified|Ministry of Textiles",
  "Traami|Tram|Copperware|A large, heavy copper platter used for serving the Wazwan communal feast.|Utility Platter|Copper, Tin|Forging, Tin-lining|18 to 24 inches diameter|Plain or rim-engraved|Weight, thickness|Thin machine-pressed sheets|Verified|Trade Usage",
  "Deg|Degh|Copperware|A massive, heavy-bottomed copper cauldron used by Wazas (chefs) to cook Wazwan.|Cooking Vessel|Copper, Tin|Forging, Tin-lining|Very Large|Plain|Thickness of base|None|Verified|Trade Usage",
  "Tash-naer|Tash-t-Naari|Copperware|A portable copper basin (Tash) and pitcher (Naer) used for handwashing before and after Wazwan.|Utility Vessel|Copper, Tin|Forging, Kandkari|Standard|Chinar, Arabesque|Engraving depth|Machine-pressed|Verified|Trade Usage",
  "Lotah|Lota|Copperware|A traditional spherical water pot with a spout.|Utility Vessel|Copper|Forging, Kandkari|8 to 10 inches|Chinar, Calligraphy|Engraving|Machine-pressed|Verified|Trade Usage",
  "Copper Plate|Rakab|Copperware|A decorative or functional copper plate, heavily engraved.|Display/Serving|Copper|Forging, Kandkari|8 to 14 inches|Calligraphy, Arabesque|Engraving|Machine-pressed|Verified|Trade Usage",
  "Copper Bowl|Kasa|Copperware|A bowl used for serving food or display, tinned inside if for food.|Servingware|Copper, Tin|Forging, Kandkari|6 to 12 inches|Chinar|Tin quality|Machine-pressed|Verified|Trade Usage",
  "Copper Jug|Naer|Copperware|A water pitcher, often heavily engraved.|Servingware|Copper|Forging, Kandkari|10 to 14 inches|Arabesque|Handle joint strength|Machine-pressed|Verified|Trade Usage",
  "Tea Set|Chai-Set|Copperware|A modern set including a teapot, sugar bowl, and milk jug in engraved copper.|Servingware|Copper, Tin|Forging, Kandkari|Standard|Chinar|Engraving|Machine-pressed|Verified|Trade Usage",
  "Spice Box|Masala-Daan|Copperware|A compartmented copper box for storing kitchen spices.|Utility Box|Copper, Tin|Forging, Kandkari|8 inches diameter|Chinar|Lid fit|Machine-pressed|Verified|Trade Usage",
  "Engraved Vase|Guldan|Copperware|A tall decorative copper vessel for dry flowers.|Display Vessel|Copper|Forging, Kandkari|12 to 24 inches|Arabesque, Birds|Engraving|Machine-pressed|Verified|Trade Usage",
  "Tin-Lined Cooking Pot|Patila|Copperware|A heavy copper pot lined with tin for daily cooking.|Cooking Vessel|Copper, Tin|Forging, Kalai (Tinning)|Varies|Plain|Tin thickness|Lead-laced tin|Verified|Trade Usage",
  "Copper Tray|Tray|Copperware|A flat serving tray, heavily engraved with Kandkari.|Servingware|Copper|Forging, Kandkari|12x18 inches|Chinar, Calligraphy|Engraving|Machine-pressed|Verified|Trade Usage",
  "Incense Burner|Isband-Soz|Copperware|A small vessel for burning Harmal (Isband) seeds during weddings/auspicious occasions.|Ritual Vessel|Copper|Forging, Kandkari|6 to 8 inches|Chinar, Geometrics|Heat resistance|Machine-pressed|Verified|Trade Usage",
  "Hookah Base|Jajeer Base|Copperware|The water chamber for a traditional Kashmiri smoking pipe.|Utility/Display|Copper|Forging, Kandkari|10 to 14 inches|Arabesque|Water tightness|Machine-pressed|Verified|Trade Usage",
  "Silver Bowl|Chandi Kasa|Silverware|A luxury display or serving bowl made of pure silver, often engraved or gilded.|Luxury Vessel|Silver, Gold (if gilded)|Engraving, Gilding|6 to 10 inches|Chinar, Lotus|Silver purity (hallmark)|Silver-plated brass|Verified|Trade Usage",
  "Silver Samovar|Chandi Samovar|Silverware|An ultra-luxury, miniaturized or full-size samovar made entirely of silver.|Luxury Display|Silver|Forging, Engraving|8 to 18 inches|Arabesque|Silver purity|Silver-plated copper|Verified|Trade Usage",
  "Silver Tray|Chandi Tray|Silverware|A silver serving tray used in royal or high-end settings.|Luxury Serving|Silver|Engraving|10x14 inches|Chinar|Silver purity|Silver-plated brass|Verified|Trade Usage",
  "Silver Teapot|Chandi Teapot|Silverware|A luxury teapot engraved in the Kashmiri style.|Luxury Serving|Silver|Engraving|Standard|Florals|Silver purity|Silver-plated brass|Technical Reference|Trade Usage",
  "Silver Box|Chandi Dabba|Silverware|A small engraved silver box for pills, jewelry, or snuff.|Luxury Box|Silver|Engraving|3 to 6 inches|Chinar, Birds|Silver purity|Silver-plated brass|Verified|Trade Usage",
  "Dejhoor|Dejhoor|Silverware / Jewelry|The traditional hexagonal ear ornament worn by Kashmiri Pandit women, suspended by a gold/silver chain (Athu).|Cultural Jewelry|Gold, Silver|Casting, Engraving|Varies|Geometrics|Metal purity|Mass-produced|Verified|General Knowledge",
  "Jiggni|Jiggni|Silverware / Jewelry|A traditional forehead ornament or pendant.|Cultural Jewelry|Gold, Silver|Casting, Filigree|Varies|Florals|Metal purity|Mass-produced|Verified|General Knowledge",
  "Silver Tumbler|Chandi Gilas|Silverware|A drinking glass made of silver, traditionally given at weddings.|Luxury Vessel|Silver|Engraving|Standard|Chinar|Silver purity|Silver-plated|Verified|Trade Usage",
  "Silver Picture Frame|Frame|Silverware|A silver-clad frame for photographs.|Home Decor|Silver, Wood base|Engraving, Repousse|5x7 inches|Florals|Silver thickness|Foil|Technical Reference|Trade Usage",
  "Kandkari Wall Panel|Copper Panel|Copperware|A flat sheet of copper heavily repoussed and engraved, framed as wall art.|Wall Art|Copper|Kandkari, Repousse|Varies|Hunting, Calligraphy|Depth of repousse|Machine-stamped|Verified|Trade Usage",
  "Copper Planter|Planter|Copperware|A large hammered copper pot for indoor plants.|Home Decor|Copper|Forging, Hammering|12 to 18 inches|Hammered texture|Water seal|Machine-pressed|Technical Reference|Trade Usage",
  "Silver Mirror|Chandi Aina|Silverware|A hand mirror or wall mirror with an engraved silver frame.|Luxury Decor|Silver, Glass|Engraving|Varies|Chinar|Silver purity|Silver-plated|Technical Reference|Trade Usage",
  "Silver Cutlery|Cutlery|Silverware|A set of spoons/forks with Kashmiri engraved handles.|Luxury Serving|Silver|Engraving|Standard|Chinar|Silver purity|Silver-plated|Technical Reference|Trade Usage",
  "Gilded Copper Bowl|Zarcod Kasa|Copperware|A copper bowl covered in real gold leaf or plating.|Luxury Display|Copper, Gold|Gilding (Zarcodi)|6 to 10 inches|Arabesque|Gold quality|Fake gold paint|Verified|Trade Usage",
  "Tumbaknari (Copper)|Copper Drum|Copperware|A decorative, non-functional version of the clay goblet drum made in copper.|Display|Copper|Forging, Kandkari|12 inches|Chinar|Engraving|Machine-pressed|Requires Field Validation|Trade Usage",

  // 181-200: Willow Wicker, Kangri & Others
  "Kangri|Kanger|Willow Wicker & Kangri|The traditional Kashmiri personal heater; an earthen pot woven into a wicker basket with a handle.|Utility Heating|Clay (Kondal), Willow Wicker|Pottery, Wicker Weaving|6 to 10 inches|Geometric weaves, dyed wicker|Strength of wicker, heat retention|Plastic replicas|Verified|Trade Usage",
  "Bridal Kangri|Maharani Kanger|Willow Wicker & Kangri|A highly decorated, colorful Kangri with silver chains and mirrors, gifted during weddings.|Ritual/Gift|Clay, Wicker, Silver/Foil|Wicker Weaving, Embellishment|10 inches|Intricate dyed patterns|Weave tightness|Mass-produced|Verified|Trade Usage",
  "Willow Basket|Tokri|Willow Wicker & Kangri|A generic, sturdy woven basket for carrying apples, bread, or goods.|Utility|Willow Wicker|Plaiting, Twining|Varies|Plain|Durability|Plastic/synthetic|Verified|Trade Usage",
  "Wicker Tray|Wicker Tray|Willow Wicker & Kangri|A flat woven tray for serving bread or tea.|Servingware|Willow Wicker|Wicker Weaving|12 to 16 inches|Plain or dyed borders|Flatness|Synthetic rattan|Verified|Trade Usage",
  "Picnic Basket|Picnic Basket|Willow Wicker & Kangri|A large basket with a lid and handle, often exported.|Utility|Willow Wicker|Wicker Weaving|18x12x10 inches|Plain|Hinge strength|Synthetic rattan|Technical Reference|Trade Usage",
  "Bread Basket|Tchot Tokri|Willow Wicker & Kangri|A round or oval basket specifically used for Kashmiri local breads (Tchot, Girda).|Utility|Willow Wicker|Wicker Weaving|10 to 14 inches|Plain|Durability|Synthetic|Verified|Trade Usage",
  "Fruit Basket|Fruit Bowl|Willow Wicker & Kangri|A decorative woven bowl for holding fruit.|Utility/Decor|Willow Wicker|Wicker Weaving|10 to 12 inches|Dyed patterns|Symmetry|Synthetic|Technical Reference|Trade Usage",
  "Storage Basket|Laundry Basket|Willow Wicker & Kangri|A large, tall basket with a lid for clothes or storage.|Home Decor|Willow Wicker|Wicker Weaving|24 to 36 inches tall|Plain|Sturdiness|Synthetic|Technical Reference|Trade Usage",
  "Decorative Basket|Decor Basket|Willow Wicker & Kangri|Small, finely woven baskets dyed in bright colors for export/tourists.|Souvenir|Willow Wicker|Wicker Weaving|4 to 8 inches|Dyed stripes|Weave fineness|Synthetic|Technical Reference|Trade Usage",
  "Wicker Furniture|Wicker Chair|Willow Wicker & Kangri|Chairs, tables, and sofas woven from thick willow branches over a wooden/metal frame.|Furniture|Willow Wicker, Wood/Metal|Wicker Weaving|Standard|Plain|Load bearing strength|Plastic rattan|Verified|Trade Usage",
  "Wicker Lamp Shade|Lamp Shade|Willow Wicker & Kangri|A woven pendant lamp shade that casts geometric shadows.|Home Decor|Willow Wicker|Open Weaving|12 to 18 inches|Open lattice|Symmetry|Synthetic|Technical Reference|Trade Usage",
  "Tumbaknari|Tumbak|Pottery|A traditional Kashmiri goblet drum used by women during weddings and celebrations.|Musical Instrument|Clay, Sheep Skin|Throwing, Skin Stretching|12 to 18 inches|Plain or painted|Resonance of skin|Synthetic drum heads|Verified|Trade Usage",
  "Kondal|Kangri Pot|Pottery|The unglazed earthen pot that sits inside the wicker Kangri to hold the hot coals.|Utility Pottery|Clay|Throwing, Firing|5 to 8 inches|Plain|Heat resistance|Poorly fired clay|Verified|Trade Usage",
  "Noet|Water Pot|Pottery|A large earthen pitcher used historically for storing water, also used as a percussion instrument.|Utility/Musical|Clay|Throwing, Firing|18 to 24 inches|Plain|Porosity|Plastic/Metal substitutes|Verified|Trade Usage",
  "Kashmiri Leather Bag|Charm Bag|Leather Craft|A handcrafted leather bag, sometimes featuring embossed or embroidered motifs.|Accessory|Sheep/Goat Leather|Tanning, Stitching, Embossing|Varies|Geometrics|Leather softness|Synthetic PU leather|Requires Field Validation|Trade Usage",
  "Leather Jacket|Leather Jacket|Leather Craft|Garments made from fine Kashmiri sheep leather, a major export industry.|Garment|Sheep Leather|Tanning, Tailoring|Standard|Plain|Leather suppleness|Fake leather|Verified|Trade Usage",
  "Kanz|Mortar|Stone Carving|A heavy, hand-carved stone mortar historically used with a wooden pestle (Muhul) to pound rice or spices.|Utility Stone|Limestone/Sandstone|Stone Chiseling|18 to 24 inches|Plain or Lotus base|Stone durability|Concrete molds|Verified|Trade Usage",
  "Stone Tombstone|Sang-e-Mazar|Stone Carving|A carved grave marker, often featuring intricate calligraphy.|Memorial Stone|Limestone|Stone Chiseling|Varies|Calligraphy, Arabesque|Carving depth|Machine routing|Verified|Trade Usage",
  "Paper Mache Elephant|Export Haathi|Papier Mâché|A mass-market souvenir elephant, heavily painted.|Souvenir|Paper Pulp, Paints|Naqashi|4 to 8 inches|Hazara|Painting quality|Wood|Technical Reference|Trade Usage",
  "Namda Animal Figure|Felt Toy|Namda (Felting)|A small, modern felted animal figure made for export.|Souvenir|Wool|Needle Felting|3 to 6 inches|Plain|Firmness|Synthetic felt|Requires Field Validation|Trade Usage"
];

export const productsData = parseProducts(rawProducts);
